import { waitForEvenAppBridge, type EvenAppBridge } from "@evenrealities/even_hub_sdk";
import { demoAgenda, parseBridge, parseIcs, when, type AgendaItem } from "./agenda/model";
import { createTextPage, updateTextPage, type TextView } from "./glasses/text";
import { getLocale, languageSelect, setLocale, tr, type Locale, type Messages } from "./i18n";
import { gestureFromEvent } from "./input/gestures";

const DEFAULT_BRIDGE = "http://127.0.0.1:8788/items";
const messages: Messages = {
  de: { controls: "Tap: {action}   Wisch: Auswahl   2x: Ende", done: "erledigt", details: "Details", empty: "Keine Termine", lede: "Kalender und Erinnerungen in einer einzigen ruhigen Tageslinie.", demo: "Demo – keine Daten verbunden", connected: "Kalender verbunden", reminder: "Erinnerung", event: "Termin", bridge: "Optionale lokale Bridge", endpoint: "Endpoint", connect: "Verbinden", import: "Kalenderdatei importieren", choose: "ICS-Datei auswählen", paste: "Oder ICS-Inhalt einfügen", load: "Importieren", help: "ICS-Dateien funktionieren direkt und bleiben auf diesem Gerät. Die Bridge ist nur für laufende Synchronisierung nötig." },
  en: { controls: "Tap: {action}   Swipe: select   2x: close", done: "complete", details: "details", empty: "No appointments", lede: "Calendar and reminders in one calm daily timeline.", demo: "Demo – no data connected", connected: "Calendar connected", reminder: "Reminder", event: "Event", bridge: "Optional local bridge", endpoint: "Endpoint", connect: "Connect", import: "Import calendar file", choose: "Choose ICS file", paste: "Or paste ICS content", load: "Import", help: "ICS files work directly and stay on this device. The bridge is only needed for continuous sync." },
  fr: { controls: "Tap: {action}   Swipe: sélectionner   2x: fermer", done: "terminer", details: "détails", empty: "Aucun rendez-vous", lede: "Calendrier et rappels dans une chronologie quotidienne claire.", demo: "Démo – aucune donnée connectée", connected: "Calendrier connecté", reminder: "Rappel", event: "Événement", bridge: "Passerelle locale facultative", endpoint: "Adresse", connect: "Connecter", import: "Importer un calendrier", choose: "Choisir un fichier ICS", paste: "Ou coller le contenu ICS", load: "Importer", help: "Les fichiers ICS restent sur cet appareil. La passerelle sert uniquement à la synchronisation continue." },
  es: { controls: "Tap: {action}   Deslizar: elegir   2x: cerrar", done: "completar", details: "detalles", empty: "Sin citas", lede: "Calendario y recordatorios en una sola línea diaria.", demo: "Demo – sin datos conectados", connected: "Calendario conectado", reminder: "Recordatorio", event: "Evento", bridge: "Puente local opcional", endpoint: "Dirección", connect: "Conectar", import: "Importar calendario", choose: "Elegir archivo ICS", paste: "O pegar contenido ICS", load: "Importar", help: "Los archivos ICS quedan en este dispositivo. El puente solo es necesario para sincronización continua." },
  it: { controls: "Tap: {action}   Scorri: seleziona   2x: chiudi", done: "completa", details: "dettagli", empty: "Nessun appuntamento", lede: "Calendario e promemoria in un'unica linea giornaliera.", demo: "Demo – nessun dato collegato", connected: "Calendario collegato", reminder: "Promemoria", event: "Evento", bridge: "Bridge locale opzionale", endpoint: "Indirizzo", connect: "Collega", import: "Importa calendario", choose: "Scegli file ICS", paste: "Oppure incolla il contenuto ICS", load: "Importa", help: "I file ICS restano su questo dispositivo. La bridge serve solo per la sincronizzazione continua." },
};

async function boot(): Promise<void> {
  const bridge: EvenAppBridge = await waitForEvenAppBridge(); let locale = getLocale(); let items: AgendaItem[] = demoAgenda(); let cursor = 0; let source = "DEMO"; let pageReady = false; let last = ""; let error = "";
  const selected = (): AgendaItem | undefined => items[cursor];
  const view = (): TextView => ({ header: `DAYLINE  ${source}`, body: [new Date().toLocaleDateString(locale, { weekday: "long", day: "2-digit", month: "long" }).toUpperCase(), "", ...items.slice(0, 7).map((item, index) => `${index === cursor ? ">" : " "} ${when(item.at, locale)} ${item.kind === "reminder" ? "[ ]" : "   "} ${item.title}`)], footer: selected() ? tr(messages, locale, "controls", { action: tr(messages, locale, selected()?.kind === "reminder" ? "done" : "details") }) : tr(messages, locale, "empty") });
  const draw = async (): Promise<void> => { const next = view(); const sig = JSON.stringify(next); if (sig === last) return; const result = pageReady ? await updateTextPage(bridge, next) : await createTextPage(bridge, next); if (result.ok) { pageReady = true; last = sig; } else pageReady = false; };
  const useItems = async (next: AgendaItem[], nextSource: string): Promise<void> => { if (!next.length) return; items = next; source = nextSource; error = ""; cursor = 0; last = ""; await draw(); renderPhone(); };
  const refresh = async (): Promise<void> => { const endpoint = localStorage.getItem("dayline.bridge") || DEFAULT_BRIDGE; try { const response = await fetch(endpoint); if (!response.ok) throw new Error(`HTTP ${response.status}`); await useItems(parseBridge(await response.json()), "BRIDGE"); } catch (cause) { source = source === "ICS" ? source : "DEMO"; error = cause instanceof Error ? cause.message : String(cause); renderPhone(); } };
  const renderPhone = (): void => { const app = document.querySelector<HTMLDivElement>("#app"); if (!app) return; app.innerHTML = `<header class="brand"><div class="brand-mark">QUIETGLASS / AGENDA</div><h1>Dayline</h1><p class="lede">${tr(messages, locale, "lede")}</p></header><section class="card">${languageSelect(locale)}</section><section class="card"><div class="status-row"><span class="status-dot ${source === "DEMO" ? "warn" : ""}"></span><strong>${tr(messages, locale, source === "DEMO" ? "demo" : "connected")}</strong></div>${error ? `<p class="hint">${error}</p>` : ""}<ol class="agenda">${items.map((item) => `<li><time>${when(item.at, locale)}</time><span>${item.title}</span><em>${tr(messages, locale, item.kind === "reminder" ? "reminder" : "event")}</em></li>`).join("")}</ol></section><section class="card"><h2>${tr(messages, locale, "import")}</h2><label>${tr(messages, locale, "choose")}<input id="ics-file" type="file" accept=".ics,text/calendar"></label><label>${tr(messages, locale, "paste")}<textarea id="ics" rows="5" placeholder="BEGIN:VCALENDAR..."></textarea></label><button id="import">${tr(messages, locale, "load")}</button><p class="hint">${tr(messages, locale, "help")}</p></section><section class="card"><h2>${tr(messages, locale, "bridge")}</h2><label>${tr(messages, locale, "endpoint")}<input id="endpoint" type="text" value="${localStorage.getItem("dayline.bridge") || DEFAULT_BRIDGE}"></label><button id="connect">${tr(messages, locale, "connect")}</button></section>`;
    document.querySelector("#language")?.addEventListener("change", (event) => { locale = (event.target as HTMLSelectElement).value as Locale; setLocale(locale); last = ""; void draw(); renderPhone(); });
    document.querySelector("#connect")?.addEventListener("click", () => { const input = document.querySelector<HTMLInputElement>("#endpoint"); if (input) localStorage.setItem("dayline.bridge", input.value.trim()); void refresh(); });
    document.querySelector("#ics-file")?.addEventListener("change", async (event) => { const file = (event.target as HTMLInputElement).files?.[0]; if (file) await useItems(parseIcs(await file.text()), "ICS"); });
    document.querySelector("#import")?.addEventListener("click", () => { const input = document.querySelector<HTMLTextAreaElement>("#ics"); if (input) void useItems(parseIcs(input.value), "ICS"); });
  };
  await draw(); renderPhone(); void refresh();
  bridge.onEvenHubEvent((event) => { const gesture = gestureFromEvent(event); if (!gesture) return; if (gesture.gesture === "doubleClick") { void bridge.shutDownPageContainer(); return; } if (gesture.gesture === "scrollDown") cursor = Math.min(items.length - 1, cursor + 1); if (gesture.gesture === "scrollUp") cursor = Math.max(0, cursor - 1); if (gesture.gesture === "click") { const item = selected(); if (item?.kind === "reminder") items = items.map((entry) => entry.id === item.id ? { ...entry, done: !entry.done, title: `${entry.done ? "" : "✓ "}${entry.title.replace(/^✓ /, "")}` } : entry); } last = ""; void draw(); });
  bridge.onDeviceStatusChanged((status) => { if (status?.connectType === "connected") { pageReady = false; last = ""; void draw(); } });
}
void boot().catch((error: unknown) => console.error("[dayline]", error));
