import { AppLocationAccuracy, CreateStartUpPageContainer, ImageContainerProperty, ImageRawDataUpdate, ImageRawDataUpdateResult, TextContainerProperty, TextContainerUpgrade, waitForEvenAppBridge, type AppLocation, type EvenAppBridge } from "@evenrealities/even_hub_sdk";
import { getLocale, languageSelect, setLocale, tr, type Locale, type Messages } from "./i18n";
import { gestureFromEvent } from "./input/gestures";
import { renderRoutePng } from "./map/draw";
import { demoRoute, parseRoute, type GeoPoint, type RouteMap } from "./map/model";

const DEFAULT_API = "http://127.0.0.1:8791/route";
const DEFAULT_DESTINATION = { lat: 47.8131, lon: 13.0458 };
const messages: Messages = {
  de: { lede: "Eine reduzierte, im Blickfeld lesbare Routenkartenansicht.", live: "Live-Route", demo: "Demo-Route", refresh: "Route laden", destination: "Ziel", latitude: "Ziel-Breitengrad", longitude: "Ziel-Laengengrad", bridge: "Route-Bridge", endpoint: "Bridge-Adresse", save: "Speichern und routen", safety: "Ziel vor der Fahrt festlegen. Die Bridge nutzt standardmaessig OSRM und kann auf deinen eigenen Server zeigen." },
  en: { lede: "A reduced route map that remains readable in your field of view.", live: "Live route", demo: "Demo route", refresh: "Load route", destination: "Destination", latitude: "Destination latitude", longitude: "Destination longitude", bridge: "Route bridge", endpoint: "Bridge address", save: "Save and route", safety: "Set the destination before driving. The bridge uses OSRM by default and can point to your own server." },
  fr: { lede: "Une carte d’itinéraire simplifiée et lisible dans votre champ de vision.", live: "Itinéraire en direct", demo: "Itinéraire démo", refresh: "Charger l’itinéraire", destination: "Destination", latitude: "Latitude de destination", longitude: "Longitude de destination", bridge: "Passerelle d’itinéraire", endpoint: "Adresse de la passerelle", save: "Enregistrer et calculer", safety: "Définissez la destination avant de conduire. La passerelle utilise OSRM par défaut ou votre propre serveur." },
  es: { lede: "Un mapa de ruta reducido y legible en el campo de visión.", live: "Ruta en directo", demo: "Ruta demo", refresh: "Cargar ruta", destination: "Destino", latitude: "Latitud del destino", longitude: "Longitud del destino", bridge: "Puente de rutas", endpoint: "Dirección del puente", save: "Guardar y calcular", safety: "Configura el destino antes de conducir. El puente usa OSRM por defecto o tu propio servidor." },
  it: { lede: "Una mappa del percorso ridotta e leggibile nel campo visivo.", live: "Percorso live", demo: "Percorso demo", refresh: "Carica percorso", destination: "Destinazione", latitude: "Latitudine destinazione", longitude: "Longitudine destinazione", bridge: "Bridge percorsi", endpoint: "Indirizzo bridge", save: "Salva e calcola", safety: "Imposta la destinazione prima di guidare. La bridge usa OSRM o il tuo server." },
};

async function boot(): Promise<void> {
  const bridge: EvenAppBridge = await waitForEvenAppBridge(); let locale = getLocale(); let route: RouteMap = demoRoute(); let position: GeoPoint | null = route.points[0] ?? null; let pageReady = false; let sending: Promise<unknown> = Promise.resolve();
  const footer = (): string => `${route.distanceMeters} m  ${route.instruction}  [${route.source.toUpperCase()}]`;
  const create = async (): Promise<void> => { const result = await bridge.createStartUpPageContainer(new CreateStartUpPageContainer({ containerTotalNum: 2, textObject: [new TextContainerProperty({ containerID: 2, containerName: "footer", xPosition: 0, yPosition: 232, width: 576, height: 54, paddingLength: 4, zOrderIndex: 3, isEventCapture: 1, content: footer() })], imageObject: [new ImageContainerProperty({ containerID: 3, containerName: "map", xPosition: 144, yPosition: 36, width: 288, height: 144, zOrderIndex: 2 })] })); pageReady = result === 0; if (pageReady) await drawMap(); };
  const drawMap = async (): Promise<void> => { if (!pageReady) return; const png = await renderRoutePng(route, position, 288, 144); sending = sending.then(async () => { const result = await bridge.updateImageRawData(new ImageRawDataUpdate({ containerID: 3, containerName: "map", imageData: png })); if (result !== ImageRawDataUpdateResult.success) console.warn("[map-glass] image update failed", result); }); await sending; await bridge.textContainerUpgrade(new TextContainerUpgrade({ containerID: 2, containerName: "footer", content: footer() })); renderPhone(); };
  const loadRoute = async (): Promise<void> => { const fix = await bridge.getAppLocation({ accuracy: AppLocationAccuracy.High }).catch(() => null); if (fix) position = { lat: fix.latitude, lon: fix.longitude }; const origin = position ?? route.points[0] ?? DEFAULT_DESTINATION; const destLat = Number(localStorage.getItem("mapglass.destLat") ?? DEFAULT_DESTINATION.lat); const destLon = Number(localStorage.getItem("mapglass.destLon") ?? DEFAULT_DESTINATION.lon); const api = localStorage.getItem("mapglass.bridge") || DEFAULT_API; const url = new URL(api); url.searchParams.set("lat", String(origin.lat)); url.searchParams.set("lon", String(origin.lon)); url.searchParams.set("destLat", String(destLat)); url.searchParams.set("destLon", String(destLon)); url.searchParams.set("lang", locale); try { const response = await fetch(url); if (!response.ok) throw new Error(`HTTP ${response.status}`); route = parseRoute(await response.json()); await drawMap(); } catch (error) { console.warn("[map-glass] route unavailable", error); renderPhone(); } };
  const renderPhone = (): void => { const app = document.querySelector<HTMLDivElement>("#app"); if (!app) return; app.innerHTML = `<header class="brand"><div class="brand-mark">QUIETGLASS / NAVIGATION</div><h1>Map Glass</h1><p class="lede">${tr(messages, locale, "lede")}</p></header><section class="card">${languageSelect(locale)}</section><section class="card map-card"><div class="status-row"><span class="status-dot ${route.source === "demo" ? "warn" : ""}"></span><strong>${tr(messages, locale, route.source === "bridge" ? "live" : "demo")}</strong></div><div class="turn"><b>${route.distanceMeters} m</b><span>${route.instruction}</span><small>${route.road}</small></div><button id="refresh">${tr(messages, locale, "refresh")}</button></section><section class="card"><h2>${tr(messages, locale, "destination")}</h2><label>${tr(messages, locale, "latitude")}<input id="dest-lat" type="text" value="${localStorage.getItem("mapglass.destLat") ?? DEFAULT_DESTINATION.lat}"></label><label>${tr(messages, locale, "longitude")}<input id="dest-lon" type="text" value="${localStorage.getItem("mapglass.destLon") ?? DEFAULT_DESTINATION.lon}"></label><h2>${tr(messages, locale, "bridge")}</h2><label>${tr(messages, locale, "endpoint")}<input id="endpoint" type="text" value="${localStorage.getItem("mapglass.bridge") || DEFAULT_API}"></label><button id="save">${tr(messages, locale, "save")}</button><p class="hint">${tr(messages, locale, "safety")}</p></section>`;
    document.querySelector("#language")?.addEventListener("change", (event) => { locale = (event.target as HTMLSelectElement).value as Locale; setLocale(locale); renderPhone(); void loadRoute(); });
    document.querySelector("#refresh")?.addEventListener("click", () => { void loadRoute(); });
    document.querySelector("#save")?.addEventListener("click", () => { const lat = document.querySelector<HTMLInputElement>("#dest-lat"); const lon = document.querySelector<HTMLInputElement>("#dest-lon"); const endpoint = document.querySelector<HTMLInputElement>("#endpoint"); if (lat) localStorage.setItem("mapglass.destLat", lat.value); if (lon) localStorage.setItem("mapglass.destLon", lon.value); if (endpoint) localStorage.setItem("mapglass.bridge", endpoint.value.trim()); void loadRoute(); });
  };
  await create(); renderPhone(); void loadRoute(); await bridge.startAppLocationUpdates({ accuracy: AppLocationAccuracy.High, distanceFilter: 8 }).catch(() => false);
  bridge.onAppLocationChanged((location: AppLocation) => { position = { lat: location.latitude, lon: location.longitude }; void drawMap(); });
  bridge.onEvenHubEvent((event) => { const gesture = gestureFromEvent(event); if (!gesture) return; if (gesture.gesture === "doubleClick") { void bridge.stopAppLocationUpdates().finally(() => bridge.shutDownPageContainer()); return; } if (gesture.gesture === "click" || gesture.gesture.startsWith("scroll")) void loadRoute(); });
  bridge.onDeviceStatusChanged((status) => { if (status?.connectType === "connected") { pageReady = false; void create(); } });
}
void boot().catch((error: unknown) => console.error("[map-glass]", error));
