import { waitForEvenAppBridge, type EvenAppBridge } from "@evenrealities/even_hub_sdk";
import { createTextPage, updateTextPage, type TextView } from "./glasses/text";
import { getLocale, languageSelect, setLocale, tr, type Locale, type Messages } from "./i18n";
import { gestureFromEvent } from "./input/gestures";
import { demoCaptions, parsePodcastFeed, parseTranscript, type Caption } from "./podcast/parse";

const DEFAULT_API = "http://127.0.0.1:8789";
const messages: Messages = {
  de: { controls: "Tap: Start/Pause   Wisch: Text   2x: Ende", lede: "Podcast-Untertitel aus offenen RSS-Transkripten oder einer lokalen Datei.", connected: "Transkript geladen", demo: "Demo-Transkript", play: "Abspielen", pause: "Pause", import: "Transkript direkt importieren", file: "VTT-, SRT-, JSON- oder Textdatei", title: "Episodentitel", load: "Datei laden", bridge: "Optionale Podcast-Bridge", endpoint: "Bridge-Adresse", connect: "Feed laden", help: "Der Direktimport funktioniert ohne Server. Die Bridge liest podcast:transcript aus deinem konfigurierten RSS-Feed." },
  en: { controls: "Tap: play/pause   Swipe: text   2x: close", lede: "Podcast captions from open RSS transcripts or a local file.", connected: "Transcript loaded", demo: "Demo transcript", play: "Play", pause: "Pause", import: "Import transcript directly", file: "VTT, SRT, JSON or text file", title: "Episode title", load: "Load file", bridge: "Optional podcast bridge", endpoint: "Bridge address", connect: "Load feed", help: "Direct import works without a server. The bridge reads podcast:transcript from your configured RSS feed." },
  fr: { controls: "Tap: lecture/pause   Swipe: texte   2x: fermer", lede: "Sous-titres de podcasts depuis un flux RSS ouvert ou un fichier local.", connected: "Transcription chargée", demo: "Transcription démo", play: "Lecture", pause: "Pause", import: "Importer une transcription", file: "Fichier VTT, SRT, JSON ou texte", title: "Titre de l’épisode", load: "Charger", bridge: "Passerelle podcast facultative", endpoint: "Adresse de la passerelle", connect: "Charger le flux", help: "L’import direct fonctionne sans serveur. La passerelle lit podcast:transcript dans le flux RSS configuré." },
  es: { controls: "Tap: reproducir/pausa   Deslizar: texto   2x: cerrar", lede: "Subtítulos de podcasts desde RSS abierto o un archivo local.", connected: "Transcripción cargada", demo: "Transcripción demo", play: "Reproducir", pause: "Pausa", import: "Importar transcripción", file: "Archivo VTT, SRT, JSON o texto", title: "Título del episodio", load: "Cargar", bridge: "Puente de podcast opcional", endpoint: "Dirección del puente", connect: "Cargar feed", help: "La importación directa funciona sin servidor. El puente lee podcast:transcript del RSS configurado." },
  it: { controls: "Tap: play/pausa   Scorri: testo   2x: chiudi", lede: "Sottotitoli podcast da RSS aperti o da un file locale.", connected: "Trascrizione caricata", demo: "Trascrizione demo", play: "Riproduci", pause: "Pausa", import: "Importa trascrizione", file: "File VTT, SRT, JSON o testo", title: "Titolo episodio", load: "Carica", bridge: "Bridge podcast opzionale", endpoint: "Indirizzo bridge", connect: "Carica feed", help: "L’importazione diretta funziona senza server. La bridge legge podcast:transcript dal feed RSS configurato." },
};

async function boot(): Promise<void> {
  const bridge: EvenAppBridge = await waitForEvenAppBridge(); let locale = getLocale(); let captions: Caption[] = demoCaptions(); let episode = "Demo episode"; let cursor = 0; let playing = false; let source = "DEMO"; let pageReady = false; let last = ""; let timer: ReturnType<typeof setInterval> | undefined;
  const view = (): TextView => ({ header: `PODCAPTION  ${playing ? "PLAY" : "PAUSE"}  ${source}`, body: [episode.toUpperCase(), "", ...captions.slice(cursor, cursor + 4).flatMap((caption) => [`${formatTime(caption.start)}  ${caption.text}`, ""])], footer: tr(messages, locale, "controls") });
  const draw = async (): Promise<void> => { const next = view(); const sig = JSON.stringify(next); if (sig === last) return; const result = pageReady ? await updateTextPage(bridge, next) : await createTextPage(bridge, next); if (result.ok) { pageReady = true; last = sig; } else pageReady = false; };
  const useTranscript = async (text: string, mime: string, title: string, nextSource: string): Promise<void> => { const parsed = parseTranscript(text, mime); if (!parsed.length) return; captions = parsed; episode = title || "Transcript"; source = nextSource; cursor = 0; last = ""; await draw(); renderPhone(); };
  const loadFeed = async (): Promise<void> => { const api = localStorage.getItem("podcaption.bridge") || DEFAULT_API; try { const feedResponse = await fetch(`${api}/feed`); if (!feedResponse.ok) throw new Error(`feed HTTP ${feedResponse.status}`); const first = parsePodcastFeed(await feedResponse.text())[0]; if (!first) throw new Error("feed has no podcast:transcript"); const response = await fetch(`${api}/transcript?url=${encodeURIComponent(first.transcriptUrl)}`); if (!response.ok) throw new Error(`transcript HTTP ${response.status}`); await useTranscript(await response.text(), first.transcriptType, first.title, "RSS"); } catch (error) { console.warn("[podcaption] feed unavailable", error); } };
  const toggle = (): void => { playing = !playing; clearInterval(timer); if (playing) timer = setInterval(() => { cursor = Math.min(Math.max(0, captions.length - 1), cursor + 1); if (cursor >= captions.length - 1) playing = false; last = ""; void draw(); renderPhone(); }, 4000); last = ""; void draw(); renderPhone(); };
  const renderPhone = (): void => { const app = document.querySelector<HTMLDivElement>("#app"); if (!app) return; app.innerHTML = `<header class="brand"><div class="brand-mark">QUIETGLASS / ACCESSIBILITY</div><h1>PodCaption</h1><p class="lede">${tr(messages, locale, "lede")}</p></header><section class="card">${languageSelect(locale)}</section><section class="card"><div class="status-row"><span class="status-dot ${source === "DEMO" ? "warn" : ""}"></span><strong>${tr(messages, locale, source === "DEMO" ? "demo" : "connected")}</strong></div><h2>${episode}</h2><div class="caption-preview">${captions.slice(cursor, cursor + 3).map((caption) => `<p><time>${formatTime(caption.start)}</time>${caption.text}</p>`).join("")}</div><button id="toggle">${tr(messages, locale, playing ? "pause" : "play")}</button></section><section class="card"><h2>${tr(messages, locale, "import")}</h2><label>${tr(messages, locale, "title")}<input id="title" type="text" value="${episode}"></label><label>${tr(messages, locale, "file")}<input id="transcript-file" type="file" accept=".vtt,.srt,.json,.txt,text/vtt,application/json,text/plain"></label><p class="hint">${tr(messages, locale, "help")}</p></section><section class="card"><h2>${tr(messages, locale, "bridge")}</h2><label>${tr(messages, locale, "endpoint")}<input id="endpoint" type="text" value="${localStorage.getItem("podcaption.bridge") || DEFAULT_API}"></label><button id="connect">${tr(messages, locale, "connect")}</button></section>`;
    document.querySelector("#language")?.addEventListener("change", (event) => { locale = (event.target as HTMLSelectElement).value as Locale; setLocale(locale); last = ""; void draw(); renderPhone(); });
    document.querySelector("#toggle")?.addEventListener("click", toggle);
    document.querySelector("#transcript-file")?.addEventListener("change", async (event) => { const file = (event.target as HTMLInputElement).files?.[0]; if (!file) return; const title = document.querySelector<HTMLInputElement>("#title")?.value || file.name.replace(/\.[^.]+$/, ""); const mime = file.type || (file.name.endsWith(".json") ? "application/json" : "text/vtt"); await useTranscript(await file.text(), mime, title, "FILE"); });
    document.querySelector("#connect")?.addEventListener("click", () => { const input = document.querySelector<HTMLInputElement>("#endpoint"); if (input) localStorage.setItem("podcaption.bridge", input.value.trim()); void loadFeed(); });
  };
  await draw(); renderPhone();
  bridge.onEvenHubEvent((event) => { const gesture = gestureFromEvent(event); if (!gesture) return; if (gesture.gesture === "doubleClick") { clearInterval(timer); void bridge.shutDownPageContainer(); return; } if (gesture.gesture === "click") { toggle(); return; } if (gesture.gesture === "scrollDown") cursor = Math.min(captions.length - 1, cursor + 1); if (gesture.gesture === "scrollUp") cursor = Math.max(0, cursor - 1); last = ""; void draw(); });
  bridge.onDeviceStatusChanged((status) => { if (status?.connectType === "connected") { pageReady = false; last = ""; void draw(); } });
}
function formatTime(seconds: number): string { const mins = Math.floor(seconds / 60); const secs = Math.floor(seconds % 60); return `${String(mins).padStart(2, "0")}:${String(secs).padStart(2, "0")}`; }
void boot().catch((error: unknown) => console.error("[podcaption]", error));
