import { waitForEvenAppBridge, type EvenAppBridge } from "@evenrealities/even_hub_sdk";
import { createExitRequest } from "./exit";
import { createTextPage, updateTextPage, type TextView } from "./glasses/text";
import { getLocale, languageSelect, setLocale, type Locale } from "./i18n";
import { gestureFromEvent } from "./input/gestures";
import { demoTelemetry, effectiveSport, elapsed, fetchTelemetry, nextSport, pace, paceOf, parseTimestamp, speedOf, staleAge, type Sport } from "./telemetry/model";
import { escapeHtml } from "./ui/html";
const DEFAULT_ENDPOINT = "http://127.0.0.1:8792/live";
const RUN_ICON = ["....##....", "...####...", "....##....", "...####...", "..######..", "....##....", "...###....", "..##.##...", ".##...##..", "##.....##."] as const;
const BIKE_ICON = [".....##.....", "....####....", ".....##.....", "...######...", "..##..###...", ".##..##.###.", "##..##....##", "##...######.", ".##.......##", "..###...###.", "....#####..."] as const;
const words = { de: { stale: "VERALTET", error: "Letzter Fehler", sport: "Sportart", auto: "Automatisch (Bridge)", run: "Laufen", bike: "Rad", live: "LIVE-TRAINING", demo: "DEMO", speed: "Tempo", pace: "Pace", power: "Leistung", heart: "Puls", cadence: "Kadenz", distance: "Distanz", elapsed: "Zeit", controls: "Tap: neu   Wisch: Sport   2x: Ende", lede: "Live-Werte vom Garmin, Radcomputer oder jeder JSON-Quelle.", endpoint: "Telemetrie-Bridge", save: "Speichern", help: "Die Bridge nimmt Live-JSON per POST an. Keine direkte Garmin-Anmeldung auf der Brille." }, en: { stale: "STALE", error: "Last error", sport: "Sport", auto: "Automatic (bridge)", run: "Run", bike: "Bike", live: "LIVE WORKOUT", demo: "DEMO", speed: "Speed", pace: "Pace", power: "Power", heart: "Heart rate", cadence: "Cadence", distance: "Distance", elapsed: "Time", controls: "Tap: refresh   Swipe: sport   2x: close", lede: "Live metrics from Garmin, a bike computer, or any JSON source.", endpoint: "Telemetry bridge", save: "Save", help: "The bridge accepts live JSON via POST. No Garmin credentials are stored on the glasses." }, fr: { stale: "PÉRIMÉ", error: "Dernière erreur", sport: "Sport", auto: "Automatique (passerelle)", run: "Course", bike: "Vélo", live: "ENTRAÎNEMENT LIVE", demo: "DÉMO", speed: "Vitesse", pace: "Allure", power: "Puissance", heart: "Fréquence", cadence: "Cadence", distance: "Distance", elapsed: "Temps", controls: "Tap: actualiser   Swipe: sport   2x: fermer", lede: "Mesures en direct depuis Garmin, un compteur ou une source JSON.", endpoint: "Passerelle télémétrie", save: "Enregistrer", help: "La passerelle accepte du JSON en POST. Aucun identifiant Garmin sur les lunettes." }, es: { stale: "ANTIGUO", error: "Último error", sport: "Deporte", auto: "Automático (puente)", run: "Carrera", bike: "Bici", live: "ENTRENO EN VIVO", demo: "DEMO", speed: "Velocidad", pace: "Ritmo", power: "Potencia", heart: "Pulso", cadence: "Cadencia", distance: "Distancia", elapsed: "Tiempo", controls: "Tap: actualizar   Deslizar: deporte   2x: cerrar", lede: "Métricas en vivo desde Garmin, ciclocomputador o cualquier fuente JSON.", endpoint: "Puente de telemetría", save: "Guardar", help: "El puente acepta JSON por POST. No guarda credenciales Garmin en las gafas." }, it: { stale: "VECCHIO", error: "Ultimo errore", sport: "Sport", auto: "Automatico (bridge)", run: "Corsa", bike: "Bici", live: "ALLENAMENTO LIVE", demo: "DEMO", speed: "Velocità", pace: "Passo", power: "Potenza", heart: "Battito", cadence: "Cadenza", distance: "Distanza", elapsed: "Tempo", controls: "Tap: aggiorna   Scorri: sport   2x: chiudi", lede: "Dati live da Garmin, ciclocomputer o qualsiasi fonte JSON.", endpoint: "Bridge telemetria", save: "Salva", help: "La bridge accetta JSON via POST. Nessuna credenziale Garmin sugli occhiali." } } as const;
async function boot(): Promise<void> { const bridge: EvenAppBridge = await waitForEvenAppBridge(); let locale = getLocale(); let data = demoTelemetry(); let receivedAt = Date.now(); let failed = false; let lastError = ""; let choice = localStorage.getItem("endurance.sport"); let pageReady = false; let last = ""; let timer: ReturnType<typeof setInterval> | undefined; let polling = false; let closed = false; const t = () => words[locale];
  const sport = (): Sport => effectiveSport(choice, data.sport);
  // Demo data stays DEMO; live data turns "STALE 12s" once the watch stops posting (old updatedAt) or the bridge stops answering.
  const mode = (): string => { if (data.source === "demo") return t().demo; const age = staleAge(parseTimestamp(data.updatedAt) ?? receivedAt, Date.now(), failed); return age ? `${t().stale} ${age}` : t().live; };
  const view = (): TextView => ({ header: `ENDURANCE HUD  ${mode()}`, body: [`${sport().toUpperCase()}  ${t().elapsed}: ${elapsed(data.elapsedSeconds)}  ${t().distance}: ${data.distanceKm.toFixed(1)} km`, "", sport() === "run" ? `${t().pace.toUpperCase()}  ${pace(paceOf(data))} /km` : `${t().speed.toUpperCase()}  ${speedOf(data).toFixed(1)} km/h`, `${t().power.toUpperCase()}  ${Math.round(data.powerWatts)} W`, `${t().heart.toUpperCase()}  ${Math.round(data.heartRate)} bpm`, `${t().cadence.toUpperCase()}  ${Math.round(data.cadence)} rpm`], footer: t().controls });
  const draw = async (): Promise<void> => { if (closed) return; const next = view(); const sig = JSON.stringify(next); if (sig === last) return; const icon = sport() === "run" ? RUN_ICON : BIKE_ICON; pageReady = pageReady ? await updateTextPage(bridge, next, icon) : await createTextPage(bridge, next, icon); if (pageReady) last = sig; };
  // The phone page is rebuilt on every poll; skip that while the rider is typing so the endpoint field is not wiped every 2 s.
  const phoneIdle = (): boolean => !document.activeElement?.matches("#app input, #app select");
  const refresh = async (): Promise<void> => { if (polling || closed) return; polling = true; try { data = await fetchTelemetry(localStorage.getItem("endurance.endpoint") || DEFAULT_ENDPOINT); receivedAt = Date.now(); failed = false; lastError = ""; } catch (error) { console.warn("[endurance-hud] bridge unavailable", error); failed = true; lastError = error instanceof Error ? error.message : String(error); } finally { polling = false; } await draw(); if (phoneIdle()) renderPhone(); };
  const setSport = (value: string | null): void => { choice = value === "run" || value === "bike" ? value : null; if (choice) localStorage.setItem("endurance.sport", choice); else localStorage.removeItem("endurance.sport"); void draw(); if (phoneIdle()) renderPhone(); };
  const renderPhone = (): void => { const app = document.querySelector<HTMLDivElement>("#app"); if (!app) return; const run = sport() === "run"; const warn = mode() !== t().live; app.innerHTML = `<header class="brand"><div class="brand-mark">QUIETGLASS / SPORT</div><h1>Endurance HUD</h1><p class="lede">${t().lede}</p></header><section class="card">${languageSelect(locale)}<label>${t().sport}<select id="sport">${[["", t().auto], ["bike", t().bike], ["run", t().run]].map(([value, name]) => `<option value="${value}"${(choice ?? "") === value ? " selected" : ""}>${name}</option>`).join("")}</select></label></section><section class="card"><div class="status-row"><span class="status-dot ${warn ? "warn" : ""}"></span><strong>${escapeHtml(mode())}</strong></div>${lastError ? `<p class="error">${t().error}: ${escapeHtml(lastError)}</p>` : ""}<div class="metrics"><div><b>${run ? pace(paceOf(data)) : speedOf(data).toFixed(1)}</b><span>${run ? `${t().pace} /km` : `${t().speed} km/h`}</span></div><div><b>${Math.round(data.powerWatts)}</b><span>${t().power} W</span></div><div><b>${Math.round(data.heartRate)}</b><span>${t().heart} bpm</span></div><div><b>${Math.round(data.cadence)}</b><span>${t().cadence} rpm</span></div></div></section><section class="card"><label>${t().endpoint}<input id="endpoint" type="text" value="${escapeHtml(localStorage.getItem("endurance.endpoint") || DEFAULT_ENDPOINT)}"></label><button id="save">${t().save}</button><p class="hint">${t().help}</p></section>`; document.querySelector("#language")?.addEventListener("change", (event) => { locale = (event.target as HTMLSelectElement).value as Locale; setLocale(locale); last = ""; void draw(); renderPhone(); }); document.querySelector("#sport")?.addEventListener("change", (event) => setSport((event.target as HTMLSelectElement).value)); document.querySelector("#save")?.addEventListener("click", () => { const input = document.querySelector<HTMLInputElement>("#endpoint"); if (input) localStorage.setItem("endurance.endpoint", input.value.trim()); void refresh(); }); };
  // Tap refreshes, swipe cycles the sport (saved), double tap closes — exactly what the footer says.
  // Double tap opens the system exit dialog; polling stops only once the user confirms.
  const requestExit = createExitRequest(bridge, { onConfirmed: () => { closed = true; clearInterval(timer); } }, "endurance-hud");
  await draw(); renderPhone(); void refresh(); timer = setInterval(() => void refresh(), 2000); bridge.onEvenHubEvent((event) => { const gesture = gestureFromEvent(event); if (!gesture) return; if (gesture.gesture === "doubleClick") { void requestExit(); return; } if (gesture.gesture === "click") { void refresh(); return; } if (gesture.gesture === "scrollDown" || gesture.gesture === "scrollUp") setSport(nextSport(sport(), gesture.gesture === "scrollDown" ? 1 : -1)); }); bridge.onDeviceStatusChanged((device) => { if (device?.connectType === "connected" && !closed) { pageReady = false; last = ""; void draw(); } }); }
void boot().catch((error: unknown) => console.error("[endurance-hud]", error));
