import { waitForEvenAppBridge, type EvenAppBridge } from "@evenrealities/even_hub_sdk";
import { createTextPage, updateTextPage, type TextView } from "./glasses/text";
import { getLocale, languageSelect, setLocale, type Locale } from "./i18n";
import { gestureFromEvent } from "./input/gestures";
import { demoTelemetry, elapsed, fetchTelemetry, pace } from "./telemetry/model";
const DEFAULT_ENDPOINT = "http://127.0.0.1:8792/live";
const RUN_ICON = ["....##....", "...####...", "....##....", "...####...", "..######..", "....##....", "...###....", "..##.##...", ".##...##..", "##.....##."] as const;
const BIKE_ICON = [".....##.....", "....####....", ".....##.....", "...######...", "..##..###...", ".##..##.###.", "##..##....##", "##...######.", ".##.......##", "..###...###.", "....#####..."] as const;
const words = { de: { live: "LIVE-TRAINING", demo: "DEMO", speed: "Tempo", pace: "Pace", power: "Leistung", heart: "Puls", cadence: "Kadenz", distance: "Distanz", elapsed: "Zeit", controls: "Tap: neu   Wisch: Sport   2x: Ende", lede: "Live-Werte vom Garmin, Radcomputer oder jeder JSON-Quelle.", endpoint: "Telemetrie-Bridge", save: "Speichern", help: "Die Bridge nimmt Live-JSON per POST an. Keine direkte Garmin-Anmeldung auf der Brille." }, en: { live: "LIVE WORKOUT", demo: "DEMO", speed: "Speed", pace: "Pace", power: "Power", heart: "Heart rate", cadence: "Cadence", distance: "Distance", elapsed: "Time", controls: "Tap: refresh   Swipe: sport   2x: close", lede: "Live metrics from Garmin, a bike computer, or any JSON source.", endpoint: "Telemetry bridge", save: "Save", help: "The bridge accepts live JSON via POST. No Garmin credentials are stored on the glasses." }, fr: { live: "ENTRAÎNEMENT LIVE", demo: "DÉMO", speed: "Vitesse", pace: "Allure", power: "Puissance", heart: "Fréquence", cadence: "Cadence", distance: "Distance", elapsed: "Temps", controls: "Tap: actualiser   Swipe: sport   2x: fermer", lede: "Mesures en direct depuis Garmin, un compteur ou une source JSON.", endpoint: "Passerelle télémétrie", save: "Enregistrer", help: "La passerelle accepte du JSON en POST. Aucun identifiant Garmin sur les lunettes." }, es: { live: "ENTRENO EN VIVO", demo: "DEMO", speed: "Velocidad", pace: "Ritmo", power: "Potencia", heart: "Pulso", cadence: "Cadencia", distance: "Distancia", elapsed: "Tiempo", controls: "Tap: actualizar   Deslizar: deporte   2x: cerrar", lede: "Métricas en vivo desde Garmin, ciclocomputador o cualquier fuente JSON.", endpoint: "Puente de telemetría", save: "Guardar", help: "El puente acepta JSON por POST. No guarda credenciales Garmin en las gafas." }, it: { live: "ALLENAMENTO LIVE", demo: "DEMO", speed: "Velocità", pace: "Passo", power: "Potenza", heart: "Battito", cadence: "Cadenza", distance: "Distanza", elapsed: "Tempo", controls: "Tap: aggiorna   Scorri: sport   2x: chiudi", lede: "Dati live da Garmin, ciclocomputer o qualsiasi fonte JSON.", endpoint: "Bridge telemetria", save: "Salva", help: "La bridge accetta JSON via POST. Nessuna credenziale Garmin sugli occhiali." } } as const;
async function boot(): Promise<void> { const bridge: EvenAppBridge = await waitForEvenAppBridge(); let locale = getLocale(); let data = demoTelemetry(); let pageReady = false; let last = ""; let timer: ReturnType<typeof setInterval> | undefined; let polling = false; const t = () => words[locale];
  const view = (): TextView => ({ header: `ENDURANCE HUD  ${data.source === "demo" ? t().demo : t().live}`, body: [`${data.sport.toUpperCase()}  ${t().elapsed}: ${elapsed(data.elapsedSeconds)}  ${t().distance}: ${data.distanceKm.toFixed(1)} km`, "", data.sport === "run" ? `${t().pace.toUpperCase()}  ${pace(data.paceSecPerKm)} /km` : `${t().speed.toUpperCase()}  ${data.speedKph.toFixed(1)} km/h`, `${t().power.toUpperCase()}  ${Math.round(data.powerWatts)} W`, `${t().heart.toUpperCase()}  ${Math.round(data.heartRate)} bpm`, `${t().cadence.toUpperCase()}  ${Math.round(data.cadence)} rpm`], footer: t().controls });
  const draw = async (): Promise<void> => { const next = view(); const sig = JSON.stringify(next); if (sig === last) return; const icon = data.sport === "run" ? RUN_ICON : BIKE_ICON; pageReady = pageReady ? await updateTextPage(bridge, next, icon) : await createTextPage(bridge, next, icon); if (pageReady) last = sig; };
  const refresh = async (): Promise<void> => { if (polling) return; polling = true; try { data = await fetchTelemetry(localStorage.getItem("endurance.endpoint") || DEFAULT_ENDPOINT); last = ""; await draw(); renderPhone(); } catch (error) { console.warn("[endurance-hud] bridge unavailable", error); } finally { polling = false; } };
  const renderPhone = (): void => { const app = document.querySelector<HTMLDivElement>("#app"); if (!app) return; app.innerHTML = `<header class="brand"><div class="brand-mark">QUIETGLASS / SPORT</div><h1>Endurance HUD</h1><p class="lede">${t().lede}</p></header><section class="card">${languageSelect(locale)}</section><section class="card"><div class="status-row"><span class="status-dot ${data.source === "demo" ? "warn" : ""}"></span><strong>${data.source === "demo" ? t().demo : t().live}</strong></div><div class="metrics"><div><b>${data.sport === "run" ? pace(data.paceSecPerKm) : data.speedKph.toFixed(1)}</b><span>${data.sport === "run" ? `${t().pace} /km` : `${t().speed} km/h`}</span></div><div><b>${Math.round(data.powerWatts)}</b><span>${t().power} W</span></div><div><b>${Math.round(data.heartRate)}</b><span>${t().heart} bpm</span></div><div><b>${Math.round(data.cadence)}</b><span>${t().cadence} rpm</span></div></div></section><section class="card"><label>${t().endpoint}<input id="endpoint" type="text" value="${localStorage.getItem("endurance.endpoint") || DEFAULT_ENDPOINT}"></label><button id="save">${t().save}</button><p class="hint">${t().help}</p></section>`; document.querySelector("#language")?.addEventListener("change", (event) => { locale = (event.target as HTMLSelectElement).value as Locale; setLocale(locale); last = ""; void draw(); renderPhone(); }); document.querySelector("#save")?.addEventListener("click", () => { const input = document.querySelector<HTMLInputElement>("#endpoint"); if (input) localStorage.setItem("endurance.endpoint", input.value.trim()); void refresh(); }); };
  await draw(); renderPhone(); void refresh(); timer = setInterval(() => void refresh(), 2000); bridge.onEvenHubEvent((event) => { const gesture = gestureFromEvent(event); if (!gesture) return; if (gesture.gesture === "doubleClick") { clearInterval(timer); void bridge.shutDownPageContainer().catch(() => undefined); return; } void refresh(); }); bridge.onDeviceStatusChanged((status) => { if (status?.connectType === "connected") { pageReady = false; last = ""; void draw(); } }); }
void boot().catch((error: unknown) => console.error("[endurance-hud]", error));
