import { AudioInputSource, waitForEvenAppBridge, type EvenAppBridge } from "@evenrealities/even_hub_sdk";
import { askAssistant, fitLines, isTooLong, isTooShort, joinPcm, type AssistantReply } from "./assistant/audio";
import { createTextPage, updateTextPage, type TextView } from "./glasses/text";
import { escapeHtml, getLocale, languageSelect, setLocale, tr, type Locale, type Messages } from "./i18n";
import { gestureFromEvent } from "./input/gestures";

const DEFAULT_ENDPOINT = "http://127.0.0.1:8790/ask";
const messages: Messages = {
  de: { ready: "Bereit. Halte gedrückt und sprich.", listening: "Ich höre nur jetzt zu.", thinking: "Dein Assistent verarbeitet...", assistant: "ASSISTENT", actions: "Aktionen", release: "Loslassen: senden   2x: Ende", controls: "Halten: sprechen   Tap: wiederholen   2x: Ende", denied: "Mikrofon wurde nicht freigegeben.", unreachable: "Bridge nicht erreichbar: {error}", lede: "Ein Assistent, der nur zuhört, wenn du ihn darum bittest.", micOn: "Mikrofon aktiv", processing: "Verarbeitung", micOff: "Mikrofon aus", answer: "ANTWORT", send: "Aufnahme senden", speak: "Sprechen", settings: "Eigener Assistent", endpoint: "Lokale Bridge-Adresse", save: "Speichern", privacy: "Audio wird nur nach einer bewussten Geste an deine konfigurierte Bridge gesendet.", tooShort: "Zu kurz. Halte gedrückt, während du sprichst.", hdrMic: "MIKRO AN", hdrBusy: "ARBEITET", hdrPrivate: "PRIVAT" },
  en: { ready: "Ready. Hold and speak.", listening: "I am listening only now.", thinking: "Your assistant is processing...", assistant: "ASSISTANT", actions: "Actions", release: "Release: send   2x: close", controls: "Hold: speak   Tap: repeat   2x: close", denied: "Microphone permission was denied.", unreachable: "Bridge unavailable: {error}", lede: "An assistant that listens only when you ask.", micOn: "Microphone active", processing: "Processing", micOff: "Microphone off", answer: "ANSWER", send: "Send recording", speak: "Speak", settings: "Your assistant", endpoint: "Local bridge address", save: "Save", privacy: "Audio is sent to your configured bridge only after a deliberate gesture.", tooShort: "Too short. Keep holding while you speak.", hdrMic: "MIC ON", hdrBusy: "BUSY", hdrPrivate: "PRIVATE" },
  fr: { ready: "Prêt. Maintenez et parlez.", listening: "Je vous écoute uniquement maintenant.", thinking: "Votre assistant traite la demande...", assistant: "ASSISTANT", actions: "Actions", release: "Relâcher: envoyer   2x: fermer", controls: "Maintenir: parler   Tap: répéter   2x: fermer", denied: "Accès au microphone refusé.", unreachable: "Passerelle inaccessible: {error}", lede: "Un assistant qui écoute seulement à votre demande.", micOn: "Microphone actif", processing: "Traitement", micOff: "Microphone coupé", answer: "RÉPONSE", send: "Envoyer l’enregistrement", speak: "Parler", settings: "Votre assistant", endpoint: "Adresse de la passerelle locale", save: "Enregistrer", privacy: "L’audio est envoyé uniquement après un geste volontaire.", tooShort: "Trop court. Maintenez pendant que vous parlez.", hdrMic: "MICRO ACTIF", hdrBusy: "OCCUPÉ", hdrPrivate: "PRIVÉ" },
  es: { ready: "Listo. Mantén pulsado y habla.", listening: "Solo estoy escuchando ahora.", thinking: "Tu asistente está procesando...", assistant: "ASISTENTE", actions: "Acciones", release: "Soltar: enviar   2x: cerrar", controls: "Mantener: hablar   Tap: repetir   2x: cerrar", denied: "No se permitió el micrófono.", unreachable: "Puente no disponible: {error}", lede: "Un asistente que solo escucha cuando se lo pides.", micOn: "Micrófono activo", processing: "Procesando", micOff: "Micrófono apagado", answer: "RESPUESTA", send: "Enviar grabación", speak: "Hablar", settings: "Tu asistente", endpoint: "Dirección del puente local", save: "Guardar", privacy: "El audio se envía únicamente tras un gesto deliberado.", tooShort: "Demasiado corto. Mantén pulsado mientras hablas.", hdrMic: "MIC ACTIVO", hdrBusy: "OCUPADO", hdrPrivate: "PRIVADO" },
  it: { ready: "Pronto. Tieni premuto e parla.", listening: "Sto ascoltando solo adesso.", thinking: "Il tuo assistente sta elaborando...", assistant: "ASSISTENTE", actions: "Azioni", release: "Rilascia: invia   2x: chiudi", controls: "Tieni: parla   Tap: ripeti   2x: chiudi", denied: "Accesso al microfono negato.", unreachable: "Bridge non raggiungibile: {error}", lede: "Un assistente che ascolta solo quando lo chiedi.", micOn: "Microfono attivo", processing: "Elaborazione", micOff: "Microfono spento", answer: "RISPOSTA", send: "Invia registrazione", speak: "Parla", settings: "Il tuo assistente", endpoint: "Indirizzo bridge locale", save: "Salva", privacy: "L’audio viene inviato solo dopo un gesto intenzionale.", tooShort: "Troppo breve. Tieni premuto mentre parli.", hdrMic: "MIC ATTIVO", hdrBusy: "OCCUPATO", hdrPrivate: "PRIVATO" },
};

async function boot(): Promise<void> {
  const bridge: EvenAppBridge = await waitForEvenAppBridge(); let locale = getLocale(); let listening = false; let busy = false; let chunks: Uint8Array[] = []; let reply: AssistantReply = { heard: "", answer: tr(messages, locale, "ready"), actions: [] }; let pageReady = false; let last = ""; let starting = false; let stopPending = false; let recorded = 0;
  const view = (): TextView => ({ header: `COMPANION  ${tr(messages, locale, listening ? "hdrMic" : busy ? "hdrBusy" : "hdrPrivate")}`, body: [listening ? tr(messages, locale, "listening") : busy ? tr(messages, locale, "thinking") : tr(messages, locale, "assistant"), "", ...fitLines(reply.answer, 54, 6), ...(reply.actions.length ? ["", ...fitLines(`${tr(messages, locale, "actions")}: ${reply.actions.join(" · ")}`, 54, 2)] : [])], footer: tr(messages, locale, listening ? "release" : "controls") });
  const draw = async (): Promise<void> => { const next = view(); const sig = JSON.stringify(next); if (sig === last) return; const result = pageReady ? await updateTextPage(bridge, next) : await createTextPage(bridge, next); if (result.ok) { pageReady = true; last = sig; } else pageReady = false; };
  const start = async (): Promise<void> => { if (listening || busy || starting) return; starting = true; stopPending = false; chunks = []; recorded = 0; const ok = await bridge.audioControl(true, AudioInputSource.Glasses).catch(() => false); starting = false; if (!ok) { stopPending = false; reply = { heard: "", answer: tr(messages, locale, "denied"), actions: [] }; await draw(); renderPhone(); return; } listening = true; if (stopPending) { stopPending = false; await stop(); return; } last = ""; await draw(); renderPhone(); };
  const stop = async (): Promise<void> => { if (starting) { stopPending = true; return; } if (!listening) return; listening = false; busy = true; await bridge.audioControl(false).catch(() => undefined); last = ""; await draw(); const pcm = joinPcm(chunks); chunks = []; recorded = 0; if (isTooShort(pcm)) { reply = { heard: "", answer: tr(messages, locale, "tooShort"), actions: [] }; busy = false; last = ""; await draw(); renderPhone(); return; } try { const endpoint = localStorage.getItem("companion.endpoint") || DEFAULT_ENDPOINT; reply = await askAssistant(endpoint, pcm, { locale }); } catch (error) { reply = { heard: "", answer: tr(messages, locale, "unreachable", { error: error instanceof Error ? error.message : String(error) }), actions: [] }; } busy = false; last = ""; await draw(); renderPhone(); };
  const renderPhone = (): void => { const app = document.querySelector<HTMLDivElement>("#app"); if (!app) return; app.innerHTML = `<header class="brand"><div class="brand-mark">QUIETGLASS / LOCAL AI</div><h1>Companion</h1><p class="lede">${tr(messages, locale, "lede")}</p></header><section class="card">${languageSelect(locale)}</section><section class="card"><div class="status-row"><span class="status-dot ${listening ? "live" : ""}"></span><strong>${tr(messages, locale, listening ? "micOn" : busy ? "processing" : "micOff")}</strong></div><div class="assistant-answer"><small>${tr(messages, locale, "answer")}</small><p>${escapeHtml(reply.answer)}</p></div><button id="ptt">${tr(messages, locale, listening ? "send" : "speak")}</button></section><section class="card"><h2>${tr(messages, locale, "settings")}</h2><label>${tr(messages, locale, "endpoint")}<input id="endpoint" type="text" value="${escapeHtml(localStorage.getItem("companion.endpoint") || DEFAULT_ENDPOINT)}"></label><button id="save">${tr(messages, locale, "save")}</button><p class="hint">${tr(messages, locale, "privacy")}</p></section>`;
    document.querySelector("#language")?.addEventListener("change", (event) => { locale = (event.target as HTMLSelectElement).value as Locale; setLocale(locale); reply = { heard: "", answer: tr(messages, locale, "ready"), actions: [] }; last = ""; void draw(); renderPhone(); });
    document.querySelector("#ptt")?.addEventListener("click", () => { void (listening ? stop() : start()); });
    document.querySelector("#save")?.addEventListener("click", () => { const input = document.querySelector<HTMLInputElement>("#endpoint"); if (input) localStorage.setItem("companion.endpoint", input.value.trim()); });
  };
  await draw(); renderPhone();
  bridge.onEvenHubEvent((event) => { const pcm = (event as { audioEvent?: { audioPcm?: unknown } }).audioEvent?.audioPcm; if (listening && pcm instanceof Uint8Array) { chunks.push(pcm); recorded += pcm.length; if (isTooLong(recorded)) void stop(); return; } const gesture = gestureFromEvent(event); if (!gesture) return; if (gesture.gesture === "doubleClick") { void bridge.audioControl(false).catch(() => false).then(() => bridge.shutDownPageContainer()).catch(() => undefined); return; } if (gesture.gesture === "longPress") { void start(); return; } if (gesture.gesture === "longPressRelease") { void stop(); return; } if (gesture.gesture === "click") { last = ""; void draw(); } });
  bridge.onDeviceStatusChanged((status) => { if (status?.connectType === "connected") { pageReady = false; last = ""; void draw(); } });
}
void boot().catch((error: unknown) => console.error("[companion]", error));
