export interface Position { readonly provider: "polymarket" | "kalshi"; readonly title: string; readonly outcome: string; readonly quantity: number; readonly currentValue: number; readonly pnl: number; readonly price: number; }
function number(value: unknown): number { const parsed = Number(value); return Number.isFinite(parsed) ? parsed : 0; }
export function parsePositions(value: unknown): Position[] { const rows = Array.isArray(value) ? value : (value as { positions?: unknown })?.positions; if (!Array.isArray(rows)) throw new Error("positions response must be an array"); return rows.flatMap((raw) => { const row = (raw ?? {}) as Partial<Position>; if (typeof row.title !== "string") return []; return [{ provider: row.provider === "kalshi" ? "kalshi" as const : "polymarket" as const, title: row.title, outcome: typeof row.outcome === "string" ? row.outcome : "", quantity: number(row.quantity), currentValue: number(row.currentValue), pnl: number(row.pnl), price: number(row.price) }]; }); }
export function demoPositions(): Position[] { return [{ provider: "polymarket", title: "Demo: rainfall above average?", outcome: "YES", quantity: 25, currentValue: 16.25, pnl: 2.5, price: 0.65 }, { provider: "kalshi", title: "DEMO-TEMP-80", outcome: "YES", quantity: 10, currentValue: 5.4, pnl: -0.6, price: 0.54 }]; }
// Sign follows the rounded amount, so -0.004 prints "+$0.00" rather than a loss of "-$0.00".
export function money(value: number): string { const rounded = Math.round(value * 100) / 100; return `${rounded >= 0 ? "+" : "-"}$${Math.abs(rounded).toFixed(2)}`; }
/** Probability price (0..1) as whole cents. */
export function cents(price: number): string { return `${Math.round(price * 100)}c`; }
// Counts code points, not UTF-16 units, so an emoji is never cut in half; never returns more than `length` characters.
export function shorten(text: string, length = 44): string { const chars = Array.from(text); if (chars.length <= length) return text; if (length <= 3) return chars.slice(0, Math.max(0, length)).join(""); return `${chars.slice(0, length - 3).join("")}...`; }
