import { AppLocationAccuracy, waitForEvenAppBridge, type EvenAppBridge } from "@evenrealities/even_hub_sdk";
import { createTextPage, updateTextPage, type TextView } from "./glasses/text";
import { getLocale, languageSelect, setLocale, tr, type Locale, type Messages } from "./i18n";
import { gestureFromEvent } from "./input/gestures";
import { fetchForecast, parseCoordinates } from "./rain/api";
import { clock, dayName, demoWeather, weatherKind, windCompass, type WeatherForecast } from "./rain/model";
import { renderWeatherIcons } from "./weather/icons";

const FALLBACK = { latitude: 47.8095, longitude: 13.0550 };
const messages: Messages = {
  de: { lede: "Aktuelles Wetter, Stunden- und 3-Tage-Prognose direkt auf der G2.", live: "Live-Prognose", demo: "Demo-Fallback", updating: "Aktualisiere...", controls: "Tap: neu   Wisch: Ansicht   2x: Ende", now: "JETZT", hourly: "STUNDEN", days: "3 TAGE", feels: "Gefuehlt", humidity: "Feuchte", clouds: "Wolken", wind: "Wind", gusts: "Boeen", precipitation: "Regen", highLow: "Max / Min", sun: "Sonne", chance: "Regenrisiko", refresh: "Jetzt aktualisieren", settings: "Standort", automatic: "Standort des Telefons verwenden", latitude: "Breitengrad", longitude: "Laengengrad", help: "Automatisch nutzt die Telefonposition. Manuelle Koordinaten werden nur lokal gespeichert.", clear: "Klar", cloud: "Bewoelkt", fog: "Nebel", rain: "Regen", snow: "Schnee", storm: "Gewitter" },
  en: { lede: "Current weather plus hourly and 3-day forecasts, directly on the G2.", live: "Live forecast", demo: "Demo fallback", updating: "Updating...", controls: "Tap: refresh   Swipe: view   2x: close", now: "NOW", hourly: "HOURLY", days: "3 DAYS", feels: "Feels", humidity: "Humidity", clouds: "Clouds", wind: "Wind", gusts: "Gusts", precipitation: "Rain", highLow: "High / Low", sun: "Sun", chance: "Rain chance", refresh: "Refresh now", settings: "Location", automatic: "Use phone location", latitude: "Latitude", longitude: "Longitude", help: "Automatic mode uses the phone location. Manual coordinates stay only on this device.", clear: "Clear", cloud: "Cloudy", fog: "Fog", rain: "Rain", snow: "Snow", storm: "Storm" },
  fr: { lede: "Meteo actuelle, previsions horaires et sur 3 jours directement sur la G2.", live: "Prevision en direct", demo: "Mode demo", updating: "Actualisation...", controls: "Tap: actualiser   Swipe: vue   2x: fermer", now: "MAINTENANT", hourly: "HEURES", days: "3 JOURS", feels: "Ressenti", humidity: "Humidite", clouds: "Nuages", wind: "Vent", gusts: "Rafales", precipitation: "Pluie", highLow: "Max / Min", sun: "Soleil", chance: "Risque pluie", refresh: "Actualiser", settings: "Position", automatic: "Utiliser la position du telephone", latitude: "Latitude", longitude: "Longitude", help: "Le mode automatique utilise le telephone. Les coordonnees restent sur cet appareil.", clear: "Clair", cloud: "Nuageux", fog: "Brouillard", rain: "Pluie", snow: "Neige", storm: "Orage" },
  es: { lede: "Tiempo actual y pronosticos por hora y para 3 dias directamente en la G2.", live: "Pronostico en directo", demo: "Modo demo", updating: "Actualizando...", controls: "Tap: actualizar   Deslizar: vista   2x: cerrar", now: "AHORA", hourly: "HORAS", days: "3 DIAS", feels: "Sensacion", humidity: "Humedad", clouds: "Nubes", wind: "Viento", gusts: "Rafagas", precipitation: "Lluvia", highLow: "Max / Min", sun: "Sol", chance: "Prob. lluvia", refresh: "Actualizar", settings: "Ubicacion", automatic: "Usar ubicacion del telefono", latitude: "Latitud", longitude: "Longitud", help: "El modo automatico usa el telefono. Las coordenadas quedan solo en este dispositivo.", clear: "Despejado", cloud: "Nublado", fog: "Niebla", rain: "Lluvia", snow: "Nieve", storm: "Tormenta" },
  it: { lede: "Meteo attuale e previsioni orarie e a 3 giorni direttamente sulla G2.", live: "Previsioni live", demo: "Modalita demo", updating: "Aggiornamento...", controls: "Tap: aggiorna   Scorri: vista   2x: chiudi", now: "ORA", hourly: "ORE", days: "3 GIORNI", feels: "Percepita", humidity: "Umidita", clouds: "Nuvole", wind: "Vento", gusts: "Raffiche", precipitation: "Pioggia", highLow: "Max / Min", sun: "Sole", chance: "Prob. pioggia", refresh: "Aggiorna", settings: "Posizione", automatic: "Usa la posizione del telefono", latitude: "Latitudine", longitude: "Longitudine", help: "La modalita automatica usa il telefono. Le coordinate restano solo su questo dispositivo.", clear: "Sereno", cloud: "Nuvoloso", fog: "Nebbia", rain: "Pioggia", snow: "Neve", storm: "Temporale" },
};

const round = (value: number): string => `${Math.round(value)}°`;

async function boot(): Promise<void> {
  const bridge: EvenAppBridge = await waitForEvenAppBridge();
  let locale = getLocale(); let forecast: WeatherForecast = demoWeather(); let loading = false; let error = ""; let pageReady = false; let last = ""; let page = 0;
  const condition = (code: number): string => tr(messages, locale, weatherKind(code));
  const currentLines = (): string[] => {
    const current = forecast.current; const today = forecast.daily[0];
    return [`${condition(current.weatherCode).toUpperCase()}  ${round(current.temperature)}`, `${tr(messages, locale, "feels")} ${round(current.feelsLike)}   ${tr(messages, locale, "humidity")} ${Math.round(current.humidity)}%`, `${tr(messages, locale, "wind")} ${windCompass(current.windDirection)} ${Math.round(current.windSpeed)} km/h   ${tr(messages, locale, "gusts")} ${Math.round(current.windGusts)}`, `${tr(messages, locale, "precipitation")} ${current.precipitation.toFixed(1)} mm   ${tr(messages, locale, "clouds")} ${Math.round(current.cloudCover)}%`, today ? `${tr(messages, locale, "highLow")} ${round(today.maximum)} / ${round(today.minimum)}` : "", today ? `${tr(messages, locale, "sun")} ${clock(today.sunrise, locale)} - ${clock(today.sunset, locale)}` : ""].filter(Boolean);
  };
  const hourlyLines = (): string[] => forecast.hourly.slice(0, 6).map((hour) => `${clock(hour.time, locale)}  ${round(hour.temperature).padEnd(4)} ${condition(hour.weatherCode).padEnd(10)} ${Math.round(hour.precipitationProbability)}%`);
  const dailyLines = (): string[] => forecast.daily.map((day) => `${dayName(day.date, locale).toUpperCase().padEnd(4)} ${round(day.maximum)} / ${round(day.minimum)}  ${condition(day.weatherCode).padEnd(10)} ${Math.round(day.precipitationProbability)}%`);
  const view = (): TextView => ({ header: `RAINLENS  ${[tr(messages, locale, "now"), tr(messages, locale, "hourly"), tr(messages, locale, "days")][page]}  ${forecast.source === "live" ? "LIVE" : "DEMO"}`, body: [...(page === 0 ? currentLines() : page === 1 ? hourlyLines() : dailyLines()), ...(error ? [`! ${error}`] : [])], footer: loading ? tr(messages, locale, "updating") : tr(messages, locale, "controls") });
  const draw = async (): Promise<void> => { const text = view(); const signature = JSON.stringify(text); if (signature === last) return; const next: TextView = { ...text, imageData: await renderWeatherIcons(forecast, page) }; const result = pageReady ? await updateTextPage(bridge, next) : await createTextPage(bridge, next); if (result.ok) { pageReady = true; last = signature; } else pageReady = false; };
  const coordinates = async (): Promise<{ latitude: number; longitude: number }> => { const automatic = localStorage.getItem("rainlens.auto") !== "false"; if (automatic) { const fix = await bridge.getAppLocation({ accuracy: AppLocationAccuracy.Medium }).catch(() => null); if (fix) return fix; } return parseCoordinates(localStorage.getItem("rainlens.lat"), localStorage.getItem("rainlens.lon")) ?? FALLBACK; };
  const refresh = async (): Promise<void> => { if (loading) return; loading = true; error = ""; try { await draw(); forecast = await fetchForecast(await coordinates()); } catch (cause) { error = cause instanceof Error ? cause.message : String(cause); } loading = false; last = ""; await draw(); renderPhone(); };
  const renderPhone = (): void => {
    const app = document.querySelector<HTMLDivElement>("#app"); if (!app) return; const automatic = localStorage.getItem("rainlens.auto") !== "false"; const current = forecast.current; const today = forecast.daily[0];
    app.innerHTML = `<header class="brand"><div class="brand-mark">QUIETGLASS / WEATHER</div><h1>RainLens</h1><p class="lede">${tr(messages, locale, "lede")}</p></header><section class="card compact">${languageSelect(locale)}</section><section class="card weather-card"><div class="status-row"><span class="status-dot ${forecast.source === "demo" ? "warn" : ""}"></span><strong>${tr(messages, locale, forecast.source === "live" ? "live" : "demo")}</strong><time>${clock(current.time, locale)}</time></div><div class="weather-hero"><div><span>${condition(current.weatherCode)}</span><strong>${round(current.temperature)}</strong></div><p>${tr(messages, locale, "feels")} ${round(current.feelsLike)}</p></div><div class="weather-grid"><div><span>${tr(messages, locale, "humidity")}</span><b>${Math.round(current.humidity)}%</b></div><div><span>${tr(messages, locale, "wind")}</span><b>${windCompass(current.windDirection)} ${Math.round(current.windSpeed)}</b><small>km/h</small></div><div><span>${tr(messages, locale, "precipitation")}</span><b>${current.precipitation.toFixed(1)}</b><small>mm</small></div><div><span>${tr(messages, locale, "clouds")}</span><b>${Math.round(current.cloudCover)}%</b></div></div>${error ? `<p class="error">${error}</p>` : ""}<button id="refresh">${tr(messages, locale, "refresh")}</button></section><section class="card"><div class="section-title"><h2>${tr(messages, locale, "hourly")}</h2><span>${tr(messages, locale, "chance")}</span></div><div class="hourly-strip">${forecast.hourly.slice(0, 8).map((hour) => `<div><time>${clock(hour.time, locale)}</time><b>${round(hour.temperature)}</b><span>${condition(hour.weatherCode)}</span><em>${Math.round(hour.precipitationProbability)}%</em></div>`).join("")}</div></section><section class="card"><h2>${tr(messages, locale, "days")}</h2><div class="forecast-list">${forecast.daily.map((day) => `<div><b>${dayName(day.date, locale)}</b><span>${condition(day.weatherCode)}</span><em>${round(day.maximum)} / ${round(day.minimum)}</em><small>${Math.round(day.precipitationProbability)}%</small></div>`).join("")}</div>${today ? `<div class="sun-row"><span>${tr(messages, locale, "sun")}</span><b>${clock(today.sunrise, locale)} → ${clock(today.sunset, locale)}</b></div>` : ""}</section><section class="card"><h2>${tr(messages, locale, "settings")}</h2><label class="check"><input id="automatic" type="checkbox"${automatic ? " checked" : ""}>${tr(messages, locale, "automatic")}</label><label>${tr(messages, locale, "latitude")}<input id="lat" type="text" value="${localStorage.getItem("rainlens.lat") ?? FALLBACK.latitude}"></label><label>${tr(messages, locale, "longitude")}<input id="lon" type="text" value="${localStorage.getItem("rainlens.lon") ?? FALLBACK.longitude}"></label><p class="hint">${tr(messages, locale, "help")}</p></section>`;
    document.querySelector("#language")?.addEventListener("change", (event) => { locale = (event.target as HTMLSelectElement).value as Locale; setLocale(locale); last = ""; void draw(); renderPhone(); });
    document.querySelector("#refresh")?.addEventListener("click", () => { const auto = document.querySelector<HTMLInputElement>("#automatic"); const lat = document.querySelector<HTMLInputElement>("#lat"); const lon = document.querySelector<HTMLInputElement>("#lon"); localStorage.setItem("rainlens.auto", String(auto?.checked ?? true)); if (lat) localStorage.setItem("rainlens.lat", lat.value); if (lon) localStorage.setItem("rainlens.lon", lon.value); void refresh(); });
  };
  await draw(); renderPhone(); void refresh();
  bridge.onEvenHubEvent((event) => { const gesture = gestureFromEvent(event); if (!gesture) return; if (gesture.gesture === "doubleClick") { void bridge.shutDownPageContainer(); return; } if (gesture.gesture === "click") { void refresh(); return; } if (gesture.gesture.startsWith("scroll")) { page = gesture.gesture === "scrollDown" ? (page + 1) % 3 : (page + 2) % 3; last = ""; void draw(); } });
  bridge.onDeviceStatusChanged((status) => { if (status?.connectType === "connected") { pageReady = false; last = ""; void draw(); } });
}
void boot().catch((error: unknown) => console.error("[rainlens]", error));
