import { AppLocationAccuracy, waitForEvenAppBridge, type EvenAppBridge } from "@evenrealities/even_hub_sdk";
import { createTextPage, updateTextPage, type TextView } from "./glasses/text";
import { getLocale, languageSelect, setLocale, tr, type Locale, type Messages } from "./i18n";
import { gestureFromEvent } from "./input/gestures";
import { clock, demoRain, parseOpenMeteo, rainBar, rainSummary, type RainWindow } from "./rain/model";

const FALLBACK = { latitude: 47.8095, longitude: 13.0550 };
const messages: Messages = {
  de: { dry: "Trocken in den naechsten 3 Stunden", rain: "Regen ab {time} · Spitze {peak} mm", updating: "Aktualisiere...", controls: "Tap: neu   Wisch: Zeitraum   2x: Ende", lede: "Niederschlag in 15-Minuten-Schritten – ohne Konto und API-Schluessel.", live: "Live-Prognose", demo: "Demo-Fallback", refresh: "Jetzt aktualisieren", settings: "Standort", automatic: "Standort des Telefons verwenden", latitude: "Breitengrad", longitude: "Laengengrad", help: "Automatisch nutzt die Telefonposition. Manuelle Koordinaten werden lokal gespeichert." },
  en: { dry: "Dry for the next 3 hours", rain: "Rain from {time} · peak {peak} mm", updating: "Updating...", controls: "Tap: refresh   Swipe: range   2x: close", lede: "Precipitation in 15-minute steps, without an account or API key.", live: "Live forecast", demo: "Demo fallback", refresh: "Refresh now", settings: "Location", automatic: "Use phone location", latitude: "Latitude", longitude: "Longitude", help: "Automatic mode uses the phone location. Manual coordinates stay on this device." },
  fr: { dry: "Temps sec pendant les 3 prochaines heures", rain: "Pluie dès {time} · pic {peak} mm", updating: "Actualisation...", controls: "Tap: actualiser   Swipe: période   2x: fermer", lede: "Précipitations par pas de 15 minutes, sans compte ni clé API.", live: "Prévision en direct", demo: "Mode démo", refresh: "Actualiser", settings: "Position", automatic: "Utiliser la position du téléphone", latitude: "Latitude", longitude: "Longitude", help: "Le mode automatique utilise le téléphone. Les coordonnées manuelles restent sur cet appareil." },
  es: { dry: "Sin lluvia durante las próximas 3 horas", rain: "Lluvia desde {time} · máximo {peak} mm", updating: "Actualizando...", controls: "Tap: actualizar   Deslizar: periodo   2x: cerrar", lede: "Precipitación cada 15 minutos, sin cuenta ni clave API.", live: "Pronóstico en directo", demo: "Modo demo", refresh: "Actualizar", settings: "Ubicación", automatic: "Usar ubicación del teléfono", latitude: "Latitud", longitude: "Longitud", help: "El modo automático usa el teléfono. Las coordenadas manuales quedan en este dispositivo." },
  it: { dry: "Nessuna pioggia nelle prossime 3 ore", rain: "Pioggia dalle {time} · picco {peak} mm", updating: "Aggiornamento...", controls: "Tap: aggiorna   Scorri: periodo   2x: chiudi", lede: "Precipitazioni ogni 15 minuti, senza account o chiave API.", live: "Previsioni live", demo: "Modalità demo", refresh: "Aggiorna", settings: "Posizione", automatic: "Usa la posizione del telefono", latitude: "Latitudine", longitude: "Longitudine", help: "La modalità automatica usa il telefono. Le coordinate manuali restano su questo dispositivo." },
};

async function boot(): Promise<void> {
  const bridge: EvenAppBridge = await waitForEvenAppBridge();
  let locale = getLocale(); let forecast: RainWindow = demoRain(); let loading = false; let error = ""; let pageReady = false; let last = "";
  const summary = (): string => rainSummary(forecast.points, tr(messages, locale, "dry"), tr(messages, locale, "rain"), locale);
  const view = (): TextView => ({ header: `RAINLENS  ${forecast.source === "live" ? "LIVE" : "DEMO"}`, body: [summary(), "", ...forecast.points.slice(0, 6).map((point) => `${clock(point.time, locale)}  ${rainBar(point.mm)} ${point.mm.toFixed(1)}`), ...(error ? [`! ${error}`] : [])], footer: loading ? tr(messages, locale, "updating") : tr(messages, locale, "controls") });
  const draw = async (): Promise<void> => { const next = view(); const signature = JSON.stringify(next); if (signature === last) return; const result = pageReady ? await updateTextPage(bridge, next) : await createTextPage(bridge, next); if (result.ok) { pageReady = true; last = signature; } else pageReady = false; };
  const coordinates = async (): Promise<{ latitude: number; longitude: number }> => { const automatic = localStorage.getItem("rainlens.auto") !== "false"; if (automatic) { const fix = await bridge.getAppLocation({ accuracy: AppLocationAccuracy.Medium }).catch(() => null); if (fix) return fix; } const latitude = Number(localStorage.getItem("rainlens.lat")); const longitude = Number(localStorage.getItem("rainlens.lon")); return Number.isFinite(latitude) && Number.isFinite(longitude) && (latitude !== 0 || longitude !== 0) ? { latitude, longitude } : FALLBACK; };
  const refresh = async (): Promise<void> => { loading = true; error = ""; await draw(); const position = await coordinates(); const url = new URL("https://api.open-meteo.com/v1/forecast"); url.searchParams.set("latitude", String(position.latitude)); url.searchParams.set("longitude", String(position.longitude)); url.searchParams.set("minutely_15", "precipitation"); url.searchParams.set("forecast_minutely_15", "12"); url.searchParams.set("timezone", "auto"); try { const response = await fetch(url); if (!response.ok) throw new Error(`HTTP ${response.status}`); forecast = parseOpenMeteo(await response.json()); } catch (cause) { error = cause instanceof Error ? cause.message : String(cause); } loading = false; last = ""; await draw(); renderPhone(); };
  const renderPhone = (): void => { const app = document.querySelector<HTMLDivElement>("#app"); if (!app) return; const automatic = localStorage.getItem("rainlens.auto") !== "false"; app.innerHTML = `<header class="brand"><div class="brand-mark">QUIETGLASS / WEATHER</div><h1>RainLens</h1><p class="lede">${tr(messages, locale, "lede")}</p></header><section class="card">${languageSelect(locale)}</section><section class="card"><div class="status-row"><span class="status-dot ${forecast.source === "demo" ? "warn" : ""}"></span><strong>${tr(messages, locale, forecast.source === "live" ? "live" : "demo")}</strong></div><h2>${summary()}</h2><div class="timeline">${forecast.points.slice(0, 8).map((point) => `<div><span>${clock(point.time, locale)}</span><b style="width:${Math.min(100, point.mm * 32)}%"></b><em>${point.mm.toFixed(1)} mm</em></div>`).join("")}</div><button id="refresh">${tr(messages, locale, "refresh")}</button></section><section class="card"><h2>${tr(messages, locale, "settings")}</h2><label class="check"><input id="automatic" type="checkbox"${automatic ? " checked" : ""}>${tr(messages, locale, "automatic")}</label><label>${tr(messages, locale, "latitude")}<input id="lat" type="text" value="${localStorage.getItem("rainlens.lat") ?? FALLBACK.latitude}"></label><label>${tr(messages, locale, "longitude")}<input id="lon" type="text" value="${localStorage.getItem("rainlens.lon") ?? FALLBACK.longitude}"></label><p class="hint">${tr(messages, locale, "help")}</p></section>`;
    document.querySelector("#language")?.addEventListener("change", (event) => { locale = (event.target as HTMLSelectElement).value as Locale; setLocale(locale); last = ""; void draw(); renderPhone(); });
    document.querySelector("#refresh")?.addEventListener("click", () => { const auto = document.querySelector<HTMLInputElement>("#automatic"); const lat = document.querySelector<HTMLInputElement>("#lat"); const lon = document.querySelector<HTMLInputElement>("#lon"); localStorage.setItem("rainlens.auto", String(auto?.checked ?? true)); if (lat) localStorage.setItem("rainlens.lat", lat.value); if (lon) localStorage.setItem("rainlens.lon", lon.value); void refresh(); });
  };
  await draw(); renderPhone(); void refresh();
  bridge.onEvenHubEvent((event) => { const gesture = gestureFromEvent(event); if (!gesture) return; if (gesture.gesture === "doubleClick") { void bridge.shutDownPageContainer(); return; } if (gesture.gesture === "click" || gesture.gesture.startsWith("scroll")) void refresh(); });
  bridge.onDeviceStatusChanged((status) => { if (status?.connectType === "connected") { pageReady = false; last = ""; void draw(); } });
}
void boot().catch((error: unknown) => console.error("[rainlens]", error));
