import crypto from "node:crypto";
import fs from "node:fs";
import http from "node:http";
import { pathToFileURL } from "node:url";
const polyWallet = process.env.POLYMARKET_WALLET ?? ""; const kalshiKey = process.env.KALSHI_KEY_ID ?? ""; const kalshiKeyPath = process.env.KALSHI_PRIVATE_KEY_PATH ?? ""; const kalshiBase = (process.env.KALSHI_BASE_URL ?? "https://external-api.kalshi.com").replace(/\/$/, "");
const polyConfigured = /^0x[a-fA-F0-9]{40}$/.test(polyWallet); const kalshiConfigured = Boolean(kalshiKey && kalshiKeyPath);
const num = (value) => { const parsed = Number(value); return value === null || value === undefined || value === "" || !Number.isFinite(parsed) ? null : parsed; };
// Polymarket Data API v2: GET /v2/positions?user=…&status=OPEN, payload in `data`, snake_case fields; cash_pnl is the unrealized P/L, cur_price the current price.
async function polymarket() { const url = new URL("https://data-api.polymarket.com/v2/positions"); url.searchParams.set("user", polyWallet); url.searchParams.set("status", "OPEN"); const response = await fetch(url); if (!response.ok) throw new Error(`Polymarket HTTP ${response.status}`); const body = await response.json(); return (body.data ?? []).filter((row) => num(row.size)).map((row) => ({ provider: "polymarket", title: row.title, outcome: row.outcome, quantity: num(row.size), currentValue: num(row.current_value), pnl: num(row.cash_pnl), realizedPnl: num(row.realized_pnl), price: num(row.cur_price) })); }
// Kalshi signs timestamp + method + path WITHOUT the query string (docs.kalshi.com/getting_started/api_keys).
function kalshiHeaders(path) { const timestamp = String(Date.now()); const key = fs.readFileSync(kalshiKeyPath, "utf8"); const signer = crypto.createSign("RSA-SHA256"); signer.update(`${timestamp}GET${path.split("?")[0]}`); signer.end(); const signature = signer.sign({ key, padding: crypto.constants.RSA_PKCS1_PSS_PADDING, saltLength: crypto.constants.RSA_PSS_SALTLEN_DIGEST }).toString("base64"); return { "KALSHI-ACCESS-KEY": kalshiKey, "KALSHI-ACCESS-TIMESTAMP": timestamp, "KALSHI-ACCESS-SIGNATURE": signature }; }
async function kalshiGet(path, signed) { const response = await fetch(`${kalshiBase}${path}`, signed ? { headers: kalshiHeaders(path) } : {}); if (!response.ok) throw new Error(`Kalshi HTTP ${response.status}`); return response.json(); }
/** Current price of the side held: the best bid (what the contracts would sell for now), falling back to the last trade when the book is empty. All Kalshi prices are YES-side "0.5600" dollar strings except no_bid. */
export function kalshiPrice(market, side) { if (!market) return null; const bid = num(side === "YES" ? market.yes_bid_dollars : market.no_bid_dollars); if (bid) return bid; const last = num(market.last_price_dollars); return last === null || !last ? null : side === "YES" ? last : 1 - last; }
/** GET /portfolio/positions: position_fp is signed (negative = NO), market_exposure_dollars is the cost basis, realized_pnl_dollars only locked-in P/L — so the open P/L is quantity × current price − cost basis. */
export function kalshiPosition(row, market) { const signed = num(row.position_fp) ?? 0; if (!signed) return null; const side = signed > 0 ? "YES" : "NO"; const quantity = Math.abs(signed); const cost = Math.abs(num(row.market_exposure_dollars) ?? 0); const price = kalshiPrice(market, side); const currentValue = price === null ? null : quantity * price; return { provider: "kalshi", title: market?.title || row.ticker, outcome: side, quantity, currentValue, pnl: currentValue === null ? null : currentValue - cost, realizedPnl: num(row.realized_pnl_dollars), price }; }
async function kalshi() { const rows = []; let cursor = ""; for (let page = 0; page < 20; page += 1) { const query = new URLSearchParams({ count_filter: "position", limit: "1000" }); if (cursor) query.set("cursor", cursor); const body = await kalshiGet(`/trade-api/v2/portfolio/positions?${query}`, true); rows.push(...(body.market_positions ?? []).filter((row) => num(row.position_fp))); cursor = body.cursor ?? ""; if (!cursor) break; }
  // Positions carry no market price, so one extra public (unsigned) GET /markets?tickers=… per 100 tickers fetches it.
  const markets = new Map(); const tickers = [...new Set(rows.map((row) => row.ticker))]; for (let index = 0; index < tickers.length; index += 100) { const chunk = tickers.slice(index, index + 100); const body = await kalshiGet(`/trade-api/v2/markets?${new URLSearchParams({ tickers: chunk.join(","), limit: String(chunk.length) })}`, false); for (const market of body.markets ?? []) markets.set(market.ticker, market); }
  return rows.map((row) => kalshiPosition(row, markets.get(row.ticker))).filter(Boolean); }
const demo = [{ provider: "polymarket", title: "Demo: rainfall above average?", outcome: "YES", quantity: 25, currentValue: 16.25, pnl: 2.5, price: 0.65 }, { provider: "kalshi", title: "DEMO-TEMP-80", outcome: "YES", quantity: 10, currentValue: 5.4, pnl: -0.6, price: 0.54 }];
/** Providers are queried independently: one failing yields a partial 200 with `errors`, only all configured providers failing is a 502. */
export async function collect(providers) { const results = await Promise.allSettled(providers.map((provider) => provider.load())); const errors = []; const positions = results.flatMap((result, index) => { if (result.status === "fulfilled") return result.value; errors.push({ provider: providers[index].name, message: result.reason instanceof Error ? result.reason.message : String(result.reason) }); return []; }); return { positions, errors, failed: providers.length > 0 && errors.length === providers.length }; }
async function handle(request, response) { const headers = { "content-type": "application/json; charset=utf-8", "access-control-allow-origin": "*" }; if (request.url !== "/positions") { response.writeHead(404, headers); response.end(JSON.stringify({ error: "not found" })); return; } const providers = [polyConfigured && { name: "polymarket", load: polymarket }, kalshiConfigured && { name: "kalshi", load: kalshi }].filter(Boolean); const updatedAt = new Date().toISOString(); if (!providers.length) { response.writeHead(200, headers); response.end(JSON.stringify({ positions: demo, source: "demo", updatedAt, errors: [] })); return; } const { positions, errors, failed } = await collect(providers); response.writeHead(failed ? 502 : 200, headers); response.end(JSON.stringify(failed ? { error: errors.map((item) => `${item.provider}: ${item.message}`).join("; "), errors } : { positions, source: "live", updatedAt, errors })); }
// Importable for tests; only `node examples/market-bridge.mjs` starts the server.
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) http.createServer((request, response) => { handle(request, response).catch((error) => { response.writeHead(500, { "content-type": "application/json; charset=utf-8", "access-control-allow-origin": "*" }); response.end(JSON.stringify({ error: error instanceof Error ? error.message : String(error) })); }); }).listen(8793, "127.0.0.1", () => console.log("Market Glance bridge: http://127.0.0.1:8793/positions"));
