import crypto from "node:crypto";
import fs from "node:fs";
import http from "node:http";
const polyWallet = process.env.POLYMARKET_WALLET ?? ""; const kalshiKey = process.env.KALSHI_KEY_ID ?? ""; const kalshiKeyPath = process.env.KALSHI_PRIVATE_KEY_PATH ?? ""; const kalshiBase = (process.env.KALSHI_BASE_URL ?? "https://external-api.kalshi.com").replace(/\/$/, "");
async function polymarket() { if (!/^0x[a-fA-F0-9]{40}$/.test(polyWallet)) return []; const url = new URL("https://data-api.polymarket.com/v2/positions"); url.searchParams.set("user", polyWallet); url.searchParams.set("status", "OPEN"); const response = await fetch(url); if (!response.ok) throw new Error(`Polymarket HTTP ${response.status}`); const body = await response.json(); return (body.data ?? []).map((row) => ({ provider: "polymarket", title: row.title, outcome: row.outcome, quantity: row.size, currentValue: row.current_value, pnl: row.cash_pnl, price: row.cur_price })); }
function kalshiHeaders(path) { const timestamp = String(Date.now()); const key = fs.readFileSync(kalshiKeyPath, "utf8"); const signer = crypto.createSign("RSA-SHA256"); signer.update(`${timestamp}GET${path}`); signer.end(); const signature = signer.sign({ key, padding: crypto.constants.RSA_PKCS1_PSS_PADDING, saltLength: crypto.constants.RSA_PSS_SALTLEN_DIGEST }).toString("base64"); return { "KALSHI-ACCESS-KEY": kalshiKey, "KALSHI-ACCESS-TIMESTAMP": timestamp, "KALSHI-ACCESS-SIGNATURE": signature }; }
async function kalshi() { if (!kalshiKey || !kalshiKeyPath) return []; const path = "/trade-api/v2/portfolio/positions"; const response = await fetch(`${kalshiBase}${path}`, { headers: kalshiHeaders(path) }); if (!response.ok) throw new Error(`Kalshi HTTP ${response.status}`); const data = await response.json(); return (data.market_positions ?? []).map((row) => { const quantity = Number(row.position_fp ?? 0); const exposure = Number(row.market_exposure_dollars ?? 0); return { provider: "kalshi", title: row.ticker, outcome: quantity >= 0 ? "YES" : "NO", quantity: Math.abs(quantity), currentValue: Math.abs(exposure), pnl: Number(row.realized_pnl_dollars ?? 0), price: quantity ? Math.abs(exposure / quantity) : 0 }; }); }
const demo = [{ provider: "polymarket", title: "Demo: rainfall above average?", outcome: "YES", quantity: 25, currentValue: 16.25, pnl: 2.5, price: 0.65 }, { provider: "kalshi", title: "DEMO-TEMP-80", outcome: "YES", quantity: 10, currentValue: 5.4, pnl: -0.6, price: 0.54 }];
http.createServer(async (request, response) => { const headers = { "content-type": "application/json; charset=utf-8", "access-control-allow-origin": "*" }; if (request.url !== "/positions") { response.writeHead(404, headers); response.end(JSON.stringify({ error: "not found" })); return; } try { const positions = [...await polymarket(), ...await kalshi()]; response.writeHead(200, headers); response.end(JSON.stringify({ positions: positions.length ? positions : demo, source: positions.length ? "live" : "demo", updatedAt: new Date().toISOString() })); } catch (error) { response.writeHead(502, headers); response.end(JSON.stringify({ error: error instanceof Error ? error.message : String(error) })); } }).listen(8793, "127.0.0.1", () => console.log("Market Glance bridge: http://127.0.0.1:8793/positions"));
