export interface Telemetry { readonly sport: "bike" | "run"; readonly elapsedSeconds: number; readonly speedKph: number; readonly paceSecPerKm: number; readonly powerWatts: number; readonly heartRate: number; readonly cadence: number; readonly distanceKm: number; readonly source: string; readonly updatedAt: string; }
function number(value: unknown): number { const parsed = Number(value); return Number.isFinite(parsed) ? parsed : 0; }
export function parseTelemetry(value: unknown): Telemetry { const row = (value && typeof value === "object" ? value : {}) as Partial<Telemetry>; return { sport: row.sport === "run" ? "run" : "bike", elapsedSeconds: number(row.elapsedSeconds), speedKph: number(row.speedKph), paceSecPerKm: number(row.paceSecPerKm), powerWatts: number(row.powerWatts), heartRate: number(row.heartRate), cadence: number(row.cadence), distanceKm: number(row.distanceKm), source: typeof row.source === "string" ? row.source : "bridge", updatedAt: typeof row.updatedAt === "string" ? row.updatedAt : new Date().toISOString() }; }
export function demoTelemetry(): Telemetry { return { sport: "bike", elapsedSeconds: 2540, speedKph: 31.4, paceSecPerKm: 115, powerWatts: 238, heartRate: 154, cadence: 91, distanceKm: 22.7, source: "demo", updatedAt: new Date().toISOString() }; }
export function pace(seconds: number): string { if (!Number.isFinite(seconds) || seconds <= 0) return "--:--"; const total = Math.round(seconds); const minutes = Math.floor(total / 60); return `${minutes}:${String(total % 60).padStart(2, "0")}`; }
export function elapsed(input: number): string { const seconds = Number.isFinite(input) ? Math.max(0, Math.floor(input)) : 0; const hours = Math.floor(seconds / 3600); const minutes = Math.floor((seconds % 3600) / 60); const rest = Math.floor(seconds % 60); return `${hours ? `${hours}:` : ""}${String(minutes).padStart(hours ? 2 : 1, "0")}:${String(rest).padStart(2, "0")}`; }
export interface FetchTelemetryOptions { readonly timeoutMs?: number; readonly fetchImpl?: typeof fetch; }
/** One poll of the bridge. Aborts after `timeoutMs` so a stalled bridge cannot pile up requests behind the 2 s poll. */
export async function fetchTelemetry(endpoint: string, options: FetchTelemetryOptions = {}): Promise<Telemetry> { const doFetch = options.fetchImpl ?? fetch; const controller = new AbortController(); const timeout = setTimeout(() => controller.abort(), options.timeoutMs ?? 4000); try { const response = await doFetch(endpoint, { signal: controller.signal }); if (!response.ok) throw new Error(`HTTP ${response.status}`); return parseTelemetry(await response.json()); } catch (error) { if (controller.signal.aborted) throw new Error("timed out"); throw error; } finally { clearTimeout(timeout); } }
