export interface GeoPoint { readonly lat: number; readonly lon: number; }
export interface RouteMap { readonly points: readonly GeoPoint[]; readonly instruction: string; readonly distanceMeters: number; readonly road: string; readonly source: "bridge" | "demo"; }
export interface PixelPoint { readonly x: number; readonly y: number; }
export function project(points: readonly GeoPoint[], width: number, height: number, padding = 18): PixelPoint[] {
  if (points.length === 0) return []; const lats = points.map((point) => point.lat); const lons = points.map((point) => point.lon); const minLat = Math.min(...lats); const maxLat = Math.max(...lats); const minLon = Math.min(...lons); const maxLon = Math.max(...lons); const latSpan = Math.max(0.00001, maxLat - minLat); const lonSpan = Math.max(0.00001, maxLon - minLon);
  return points.map((point) => ({ x: padding + ((point.lon - minLon) / lonSpan) * (width - padding * 2), y: height - padding - ((point.lat - minLat) / latSpan) * (height - padding * 2) }));
}
export function parseRoute(value: unknown): RouteMap { const row = value as Partial<RouteMap>; if (!Array.isArray(row.points) || row.points.length < 2) throw new Error("route needs at least two points"); const points = row.points.flatMap((point) => { const candidate = point as Partial<GeoPoint>; return Number.isFinite(candidate.lat) && Number.isFinite(candidate.lon) ? [{ lat: Number(candidate.lat), lon: Number(candidate.lon) }] : []; }); if (points.length < 2) throw new Error("route geometry is invalid"); return { points, instruction: typeof row.instruction === "string" ? row.instruction : "Route folgen", distanceMeters: Number.isFinite(row.distanceMeters) ? Number(row.distanceMeters) : 0, road: typeof row.road === "string" ? row.road : "", source: "bridge" }; }
export function demoRoute(): RouteMap { return { source: "demo", road: "Vogelweiderstrasse", instruction: "Rechts auf Sterneckstrasse", distanceMeters: 180, points: [{ lat: 47.806, lon: 13.052 }, { lat: 47.807, lon: 13.053 }, { lat: 47.808, lon: 13.054 }, { lat: 47.809, lon: 13.056 }, { lat: 47.8105, lon: 13.057 }, { lat: 47.811, lon: 13.059 }] }; }
