import { waitForEvenAppBridge, type EvenAppBridge } from "@evenrealities/even_hub_sdk";
import { createTextPage, updateTextPage, type TextView } from "./glasses/text";
import { getLocale, languageSelect, setLocale, type Locale } from "./i18n";
import { gestureFromEvent } from "./input/gestures";
import { demoPositions, money, parsePositions, shorten, type Position } from "./markets/model";
const DEFAULT_ENDPOINT = "http://127.0.0.1:8793/positions";
const words = { de: { title: "POSITIONEN", demo: "DEMO", live: "LIVE", controls: "Tap: neu   Wisch: Auswahl   2x: Ende", lede: "Read-only Positionen von Polymarket und Kalshi.", endpoint: "Lokale Markt-Bridge", save: "Speichern", empty: "Keine offenen Positionen", warning: "Nur Anzeige. Keine Orders, keine Kauf- oder Verkaufsgesten." }, en: { title: "POSITIONS", demo: "DEMO", live: "LIVE", controls: "Tap: refresh   Swipe: select   2x: close", lede: "Read-only positions from Polymarket and Kalshi.", endpoint: "Local market bridge", save: "Save", empty: "No open positions", warning: "Display only. No orders, buying, or selling gestures." }, fr: { title: "POSITIONS", demo: "DÉMO", live: "LIVE", controls: "Tap: actualiser   Swipe: choisir   2x: fermer", lede: "Positions en lecture seule de Polymarket et Kalshi.", endpoint: "Passerelle locale", save: "Enregistrer", empty: "Aucune position ouverte", warning: "Affichage uniquement. Aucun ordre ni geste d'achat ou de vente." }, es: { title: "POSICIONES", demo: "DEMO", live: "EN VIVO", controls: "Tap: actualizar   Deslizar: elegir   2x: cerrar", lede: "Posiciones de solo lectura de Polymarket y Kalshi.", endpoint: "Puente local", save: "Guardar", empty: "Sin posiciones abiertas", warning: "Solo visualización. Sin órdenes ni gestos de compra o venta." }, it: { title: "POSIZIONI", demo: "DEMO", live: "LIVE", controls: "Tap: aggiorna   Scorri: seleziona   2x: chiudi", lede: "Posizioni in sola lettura da Polymarket e Kalshi.", endpoint: "Bridge locale", save: "Salva", empty: "Nessuna posizione aperta", warning: "Solo visualizzazione. Nessun ordine o gesto di acquisto/vendita." } } as const;
async function boot(): Promise<void> { const bridge: EvenAppBridge = await waitForEvenAppBridge(); let locale = getLocale(); let positions = demoPositions(); let source = "demo"; let cursor = 0; let pageReady = false; let last = ""; let timer: ReturnType<typeof setInterval> | undefined; const t = () => words[locale];
  const visible = (): Position[] => positions.slice(cursor, cursor + 4); const view = (): TextView => ({ header: `MARKET GLANCE  ${source === "live" ? t().live : t().demo}`, body: [t().title, "", ...(visible().length ? visible().flatMap((position, index) => [`${index === 0 ? ">" : " "} ${position.provider === "kalshi" ? "K" : "P"} ${shorten(position.title, 38)}`, `  ${position.outcome} ${Math.round(position.price * 100)}c  ${money(position.pnl)}`]) : [t().empty])], footer: t().controls });
  const draw = async (): Promise<void> => { const next = view(); const sig = JSON.stringify(next); if (sig === last) return; pageReady = pageReady ? await updateTextPage(bridge, next) : await createTextPage(bridge, next); if (pageReady) last = sig; };
  const refresh = async (): Promise<void> => { try { const response = await fetch(localStorage.getItem("markets.endpoint") || DEFAULT_ENDPOINT); if (!response.ok) throw new Error(`HTTP ${response.status}`); const body = await response.json() as { positions?: unknown; source?: string }; positions = parsePositions(body); source = body.source === "live" ? "live" : "demo"; cursor = Math.min(cursor, Math.max(0, positions.length - 1)); last = ""; await draw(); renderPhone(); } catch (error) { console.warn("[market-glance] bridge unavailable", error); } };
  const renderPhone = (): void => { const app = document.querySelector<HTMLDivElement>("#app"); if (!app) return; app.innerHTML = `<header class="brand"><div class="brand-mark">QUIETGLASS / READ ONLY</div><h1>Market Glance</h1><p class="lede">${t().lede}</p></header><section class="card">${languageSelect(locale)}</section><section class="card"><div class="status-row"><span class="status-dot ${source === "demo" ? "warn" : ""}"></span><strong>${source === "live" ? t().live : t().demo}</strong></div><div class="positions">${positions.map((position) => `<article><small>${position.provider.toUpperCase()} · ${position.outcome}</small><strong>${position.title}</strong><span>${Math.round(position.price * 100)}c · ${money(position.pnl)}</span></article>`).join("") || `<p>${t().empty}</p>`}</div></section><section class="card"><label>${t().endpoint}<input id="endpoint" type="text" value="${localStorage.getItem("markets.endpoint") || DEFAULT_ENDPOINT}"></label><button id="save">${t().save}</button><p class="hint">${t().warning}</p></section>`; document.querySelector("#language")?.addEventListener("change", (event) => { locale = (event.target as HTMLSelectElement).value as Locale; setLocale(locale); last = ""; void draw(); renderPhone(); }); document.querySelector("#save")?.addEventListener("click", () => { const input = document.querySelector<HTMLInputElement>("#endpoint"); if (input) localStorage.setItem("markets.endpoint", input.value.trim()); void refresh(); }); };
  await draw(); renderPhone(); void refresh(); timer = setInterval(() => void refresh(), 15000); bridge.onEvenHubEvent((event) => { const gesture = gestureFromEvent(event); if (!gesture) return; if (gesture.gesture === "doubleClick") { clearInterval(timer); void bridge.shutDownPageContainer(); return; } if (gesture.gesture === "scrollDown") cursor = Math.min(Math.max(0, positions.length - 1), cursor + 1); if (gesture.gesture === "scrollUp") cursor = Math.max(0, cursor - 1); last = ""; void draw(); }); bridge.onDeviceStatusChanged((status) => { if (status?.connectType === "connected") { pageReady = false; last = ""; void draw(); } }); }
void boot().catch((error: unknown) => console.error("[market-glance]", error));
