import { waitForEvenAppBridge, type EvenAppBridge } from "@evenrealities/even_hub_sdk";
import { createTextPage, updateTextPage } from "./glasses/text";
import { glassesView, modeLabel, type FeedStatus } from "./glasses/view";
import { getLocale, languageSelect, setLocale, type Locale } from "./i18n";
import { gestureFromEvent } from "./input/gestures";
import { fetchPositions } from "./markets/fetch";
import { cents, demoPositions, money, staleAge } from "./markets/model";
import { escapeHtml } from "./ui/html";
const DEFAULT_ENDPOINT = "http://127.0.0.1:8793/positions";
const words = { de: { stale: "VERALTET", error: "Letzter Fehler", realized: "realisiert", title: "POSITIONEN", demo: "DEMO", live: "LIVE", controls: "Tap: neu   Wisch: Auswahl   2x: Ende", lede: "Read-only Positionen von Polymarket und Kalshi.", endpoint: "Lokale Markt-Bridge", save: "Speichern", empty: "Keine offenen Positionen", warning: "Nur Anzeige. Keine Orders, keine Kauf- oder Verkaufsgesten." }, en: { stale: "STALE", error: "Last error", realized: "realized", title: "POSITIONS", demo: "DEMO", live: "LIVE", controls: "Tap: refresh   Swipe: select   2x: close", lede: "Read-only positions from Polymarket and Kalshi.", endpoint: "Local market bridge", save: "Save", empty: "No open positions", warning: "Display only. No orders, buying, or selling gestures." }, fr: { stale: "PÉRIMÉ", error: "Dernière erreur", realized: "réalisé", title: "POSITIONS", demo: "DÉMO", live: "LIVE", controls: "Tap: actualiser   Swipe: choisir   2x: fermer", lede: "Positions en lecture seule de Polymarket et Kalshi.", endpoint: "Passerelle locale", save: "Enregistrer", empty: "Aucune position ouverte", warning: "Affichage uniquement. Aucun ordre ni geste d'achat ou de vente." }, es: { stale: "ANTIGUO", error: "Último error", realized: "realizado", title: "POSICIONES", demo: "DEMO", live: "EN VIVO", controls: "Tap: actualizar   Deslizar: elegir   2x: cerrar", lede: "Posiciones de solo lectura de Polymarket y Kalshi.", endpoint: "Puente local", save: "Guardar", empty: "Sin posiciones abiertas", warning: "Solo visualización. Sin órdenes ni gestos de compra o venta." }, it: { stale: "VECCHIO", error: "Ultimo errore", realized: "realizzato", title: "POSIZIONI", demo: "DEMO", live: "LIVE", controls: "Tap: aggiorna   Scorri: seleziona   2x: chiudi", lede: "Posizioni in sola lettura da Polymarket e Kalshi.", endpoint: "Bridge locale", save: "Salva", empty: "Nessuna posizione aperta", warning: "Solo visualizzazione. Nessun ordine o gesto di acquisto/vendita." } } as const;
async function boot(): Promise<void> { const bridge: EvenAppBridge = await waitForEvenAppBridge(); let locale = getLocale(); let positions = demoPositions(); let status: FeedStatus = { source: "demo", updatedAt: Date.now(), failed: false, errors: [] }; let lastError = ""; let cursor = 0; let pageReady = false; let last = ""; let timer: ReturnType<typeof setInterval> | undefined; let loading = false; let again = false; let closed = false; const t = () => words[locale];
  const mode = (): string => modeLabel(status, Date.now(), t());
  const view = () => glassesView(positions, cursor, { mode: mode(), title: t().title, empty: t().empty, controls: t().controls });
  const draw = async (): Promise<void> => { if (closed) return; const next = view(); const sig = JSON.stringify(next); if (sig === last) return; pageReady = pageReady ? await updateTextPage(bridge, next) : await createTextPage(bridge, next); if (pageReady) last = sig; };
  const phoneIdle = (): boolean => !document.activeElement?.matches("#app input, #app select");
  // A call while one is in flight (e.g. Save with a new endpoint) is not dropped: exactly one follow-up runs as soon as the current one ends.
  const refresh = async (): Promise<void> => { if (closed) return; if (loading) { again = true; return; } loading = true; again = false; try { const result = await fetchPositions(localStorage.getItem("markets.endpoint") || DEFAULT_ENDPOINT); positions = result.positions; status = { source: result.source, updatedAt: result.updatedAt ?? Date.now(), failed: false, errors: result.errors }; lastError = result.errors.map((error) => `${error.provider || "?"}: ${error.message}`).join("; "); cursor = Math.min(cursor, Math.max(0, positions.length - 1)); } catch (error) { console.warn("[market-glance] bridge unavailable", error); status = { ...status, failed: true }; lastError = error instanceof Error ? error.message : String(error); } finally { loading = false; } last = ""; await draw(); if (phoneIdle()) renderPhone(); if (again) await refresh(); };
  const renderPhone = (): void => { const app = document.querySelector<HTMLDivElement>("#app"); if (!app) return; const warn = status.source === "demo" || status.errors.length > 0 || staleAge(status.updatedAt, Date.now(), status.failed) !== null; app.innerHTML = `<header class="brand"><div class="brand-mark">QUIETGLASS / READ ONLY</div><h1>Market Glance</h1><p class="lede">${t().lede}</p></header><section class="card">${languageSelect(locale)}</section><section class="card"><div class="status-row"><span class="status-dot ${warn ? "warn" : ""}"></span><strong>${escapeHtml(mode())}</strong></div>${lastError ? `<p class="error">${t().error}: ${escapeHtml(lastError)}</p>` : ""}<div class="positions">${positions.map((position) => `<article><small>${escapeHtml(position.provider.toUpperCase() || "?")} · ${escapeHtml(position.outcome)}</small><strong>${escapeHtml(position.title)}</strong><span>${cents(position.price)} · ${money(position.pnl)}${position.realizedPnl === undefined ? "" : ` · ${t().realized} ${money(position.realizedPnl)}`}</span></article>`).join("") || `<p>${t().empty}</p>`}</div></section><section class="card"><label>${t().endpoint}<input id="endpoint" type="text" value="${escapeHtml(localStorage.getItem("markets.endpoint") || DEFAULT_ENDPOINT)}"></label><button id="save">${t().save}</button><p class="hint">${t().warning}</p></section>`; document.querySelector("#language")?.addEventListener("change", (event) => { locale = (event.target as HTMLSelectElement).value as Locale; setLocale(locale); last = ""; void draw(); renderPhone(); }); document.querySelector("#save")?.addEventListener("click", () => { const input = document.querySelector<HTMLInputElement>("#endpoint"); if (input) localStorage.setItem("markets.endpoint", input.value.trim()); void refresh(); }); };
  await draw(); renderPhone(); void refresh(); timer = setInterval(() => void refresh(), 15000); bridge.onEvenHubEvent((event) => { const gesture = gestureFromEvent(event); if (!gesture) return; if (gesture.gesture === "doubleClick") { closed = true; clearInterval(timer); void bridge.shutDownPageContainer().catch(() => undefined); return; } if (gesture.gesture === "click") { void refresh(); return; } if (gesture.gesture === "scrollDown") cursor = Math.min(Math.max(0, positions.length - 1), cursor + 1); if (gesture.gesture === "scrollUp") cursor = Math.max(0, cursor - 1); last = ""; void draw(); }); bridge.onDeviceStatusChanged((device) => { if (device?.connectType === "connected" && !closed) { pageReady = false; last = ""; void draw(); } }); }
void boot().catch((error: unknown) => console.error("[market-glance]", error));
